### ISSUE TITLE
File access profiling

### ISSUE THREAD

**Issue by B3ns44d** [kubernetes-sigs/security-profiles-operator#1036]
#### What would you like to be added:
A strict denylist can be created by observing the system calls that access files and obtaining a list of the files that a container is expected to access in addition to creating an allowlist (seccomp profile) that allows spacifec syscalls while blocking everything else. We want to be even more strict than that by profiling file access.

##### A list of File system calls

| Syscall           | Number | Description                                                               |
|-------------------|--------|---------------------------------------------------------------------------|
| CLOSE             |      3 | Close a file descriptor                                                   |
| CREAT             |     85 | Open and possibly create a file                                           |
| OPEN              |      2 | Open and possibly create a file                                           |
| OPENAT            |    257 | Open and possibly create a file relative to a directory file descriptor   |
| NAME_TO_HANDLE_AT |    303 | Obtain handle for a pathname                                              |
| OPEN_BY_HANDLE_AT |    304 | Open file via a handle                                                    |
| MEMFD_CREATE      |    319 | Сreate an anonymous file                                                  |
| MKNOD             |    133 | Create a special or ordinary file                                         |
| MKNODAT           |    259 | Create a special or ordinary file relative to a directory file descriptor |
| RENAME            |     82 | Rename a file                                                             |
| RENAMEAT          |    264 | Rename a file relative to directory file descriptors                      |
| RENAMEAT          |    316 | Rename a file relative to directory file descriptors                      |
| TRUNCATE          |     76 | Truncate a file to a specified length                                     |
| FTRUNCATE         |     77 | Truncate a file to a specified length                                     |
| FALLOCATE         |    285 | Manipulate file space                                                     |

#### Why is this needed:
We can restrict file access as a part of apparmor/selinux profile, and this will help make the file profiling a straightforward process

**Comment by saschagrunert** [comment]
Hey @B3ns44d, thank you for the request. It feels to me that is something we can achieve via SELinux and AppArmor already. @pjbgf @jhrozek @JAORMX what do you think?

**Comment by JAORMX** [comment]
@saschagrunert I agree, this is not exactly the realm for Seccomp, but instead the job for a Mandatory Access Control implementation like SELinux and AppArmor. With SELinux (and I'm sure with AppArmor also) it's possible to restrict the files to be accessed and the allowed operations.

**Comment by B3ns44d** [comment]
@saschagrunert, @JAORMX Yes, that's exactly what I wanted to say; to enhance the denylist policy, we can create a profile (AppArmor/SELinux) that restricts file access. The purpose here is to determine whether it is possible to automatically record file access and generate a denylist from it.

for example this is a list of files that a nginx container is expected to access:

```
openat /etc/ld.so.cache
openat /lib/x86_64-linux-gnu/libdl.so.2
openat /lib/x86_64-linux-gnu/libpthread.so.0
openat /lib/x86_64-linux-gnu/libcrypt.so.1
openat /lib/x86_64-linux-gnu/libpcre.so.3
openat /usr/lib/x86_64-linux-gnu/libssl.so.1.1
openat /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
openat /lib/x86_64-linux-gnu/libz.so.1
openat /lib/x86_64-linux-gnu/libc.so.6
openat /etc/localtime
openat /var/log/nginx/error.log
openat /usr/lib/ssl/openssl.cnf
openat /sys/devices/system/cpu/online
openat /etc/nginx/nginx.conf
openat /etc/nsswitch.conf
openat /etc/ld.so.cache
openat /lib/x86_64-linux-gnu/libnss_files.so.2
openat /etc/passwd
openat /etc/group
openat /etc/nginx/mime.types
openat /etc/nginx/conf.d
openat /etc/nginx/conf.d/default.conf
openat /var/log/nginx/error.log
openat /var/log/nginx/access.log
openat /var/run/nginx.pid
openat /proc/sys/kernel/ngroups_max
openat /etc/group
....
```
so we may therefore create a SELinux or AppArmor profile that only permits specific files by recording file access.

**Comment by B3ns44d** [comment]
@JAORMX yes yes, I have been recording seccomp profiles using the "ProfileRecording" for a while now. However, for some reason, I was unable to record SELinux profiles (I don't have a lot of experience with SELinux, _I'd appreciate it if you could share any resources with me on SELinux and SPO.). 

So, I'm wondering if the SPO can detect/record file access and generate an Apparmor profile from it, I think that at this time, it isn't feasible to do so. 

The prevention policy that I'm creating consists of the following:

- Syscalls
	- a Seccomp policy that drops system calls that are unsafe and typically unnecessary for container operation and only allows a subset of system calls
- File Access
	- Creating a list of files that a container is expected to access and pass it to a Apparmor profile as allowlist, This will help alert on or prevent opening files outside the expected profile.
- Executable
	- Same as file access. This will help determining how many executable programs should run in a container.
- Capabilities
	- Determining a set of capabilities that a container needs to make.

along with a policy for alerting based on the above as well.

**Comment by pjbgf** [comment]
@B3ns44d we are yet to support auto generation of AppArmor profiles. In the mean time, you are better off using the AppArmor tools and creating them manually.

You can use the "[systemic approach](https://documentation.suse.com/sles/12-SP5/html/SLES-all/cha-apparmor-commandline.html#sec-apparmor-commandline-profiling-systemic)" for it, which is quite straightforward - provided you have admin access to one of your worker nodes. Just notice that (AFAIK) both `aa-logprof` and `aa-genprof` won't be helpful for generating profiles for executables outside the same `chroot` they are running in.

I generally start my profiling sessions with a basic [AppArmor template](https://gist.github.com/pjbgf/f0b93cda3f4e7e1b51080e05105a00e6). I set the profile to complain mode and then manually add the required new perms as they emerge, then reset them to complain mode. This forces the profile changes to be reloaded. And then keep doing this until no new entries appear in the audit logs after running the application.

**Comment by B3ns44d** [comment]
@pjbgf AFAIU the "aa-genprof" is used to generate AppArmor profiles from programs based on system logs "/var/log/audit/audit.log," but I'm not sure how this would apply to pods.

**Comment by pjbgf** [comment]
@B3ns44d yes, that's due to the fact that by default your container binaries will reside in a different chroot and PID namespace as the `aa-genprof` tooling. You probably can circumvent that at the risk of potentially influencing the resulting profile. Hence why so far I am still going for a mostly manual approach on AppArmor.  But I haven't spent enough time trying to automating it yet.

Potentially using SPOD's log enricher features could lead to an optimised way of improving/creating AppArmor profiles for Kubernetes workloads. But we are not quite there yet.
