### ISSUE TITLE
security: Authenticate build tooling

### ISSUE THREAD

**Issue by stephen-fox** [kubernetes-sigs/security-profiles-operator#1041]
#### What would you like to be added:
Currently, the `Makefile` automation downloads tools like `kustomize`, `kubernetes-split-yaml`, and `operator-sdk` without authenticating them. In other words, their hashes are not checked, or they are not built from source using `go install` (assuming they are written in Go). The latter method ensures the source code and its dependencies match what is in Google's sum database. This is potentially more convenient because it eliminates the need to carry around hashes for platform-specific executables. For more information about Go dependency authentication, refer to: https://go.dev/ref/mod#authenticating

#### Why is this needed:
Supply chain security.

#### User story covered
I am not really sure what to put here... it looks like all the user stories desire some level of security. I am open to guidance about editing this to something else. This issue could also be changed to a bug - I was not sure what to select.

**Comment by saschagrunert** [comment]
@stephen-fox great points and I totally agree that we should verify their integrity! Do you mind creating a PR for that?

**Comment by JAORMX** [comment]
@stephen-fox we are doing this for other dependencies, you might wanna look at this if you want ideas https://github.com/kubernetes-sigs/security-profiles-operator/pull/1040
