### ISSUE TITLE
Clean up profiles when ConfigMap deleted

### ISSUE THREAD

**Issue by hasheddan** [kubernetes-sigs/security-profiles-operator#106]
#### What would you like to be added:

Currently profiles are not cleaned up on a node when their `ConfigMap` is deleted. The lifecycle of the profile on a node should match that of the `ConfigMap` that created it.

#### Why is this needed:

In most cases it is actually fine for the profile to be orphaned. In fact, cleaning up a profile after a workload has started using it can be a problem if that workload restarts and the profile is no longer there. However, there are a few cases in which orphaning profiles can be a problem:
- A user creates a profile that is overly permissive or has a typo and does not want it to be able to be applied to containers anymore.
- A user creates a new profile with a similar name to an old one that no longer exists as a `ConfigMap`, but still exists on the node. They then create a workload and accidentally apply the old profile. The operator would not block this because it would be using a valid profile, but it would be unexpected and potentially difficult to troubleshoot.
- A user cannot get an accurate global list of seccomp profiles without interacting with each node.

**Comment by saschagrunert** [comment]
@hasheddan do you still plan to work on this or can someone else take it? :)
