### ISSUE TITLE
BPF recorder not working

### ISSUE THREAD

**Issue by pradeepjairamani** [kubernetes-sigs/security-profiles-operator#1092]
#### What happened:
I was trying to launch the BPF recorder using 
#### What you expected to happen:
Running BPF recorder using the below manifest file
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: my-recording
spec:
  kind: SeccompProfile
  recorder: bpf
  podSelector:
    matchLabels:
      app: zookeeper

#### How to reproduce it (as minimally and precisely as possible):
I0818 08:57:14.508848   25619 bpfrecorder.go:125] bpf-recorder "msg"="Starting log-enricher on node: ip-10-127-0-126.ap-south-1.compute.internal"
I0818 08:57:14.509644   25619 bpfrecorder.go:156] bpf-recorder "msg"="Connecting to metrics server"
I0818 08:57:14.512370   25619 bpfrecorder.go:176] bpf-recorder "msg"="Got system mount namespace: 4026531840"
I0818 08:57:14.512384   25619 bpfrecorder.go:178] bpf-recorder "msg"="Doing BPF load/unload self-test"
I0818 08:57:14.512393   25619 bpfrecorder.go:377] bpf-recorder "msg"="Loading bpf module"
I0818 08:57:14.512412   25619 bpfrecorder.go:446] bpf-recorder "msg"="Using system btf file"
I0818 08:57:14.512573   25619 bpfrecorder.go:397] bpf-recorder "msg"="Loading bpf object from module"
libbpf: map 'events': failed to create: Invalid argument(-22)
libbpf: failed to load object 'recorder.bpf.o'
E0818 08:57:14.517369   25619 logr.go:279] setup "msg"="running security-profiles-operator" "error"="load self-test: load bpf object: failed to load BPF object"
Error from server (BadRequest): container "bpf-recorder" in pod "spod-szd6j" is waiting to start: PodInitializing
#### Environment:
- EKS
- OS (e.g: `cat /etc/os-release`):
- NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
- Kernel (e.g. `uname -a`): 5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by saschagrunert** [comment]
Hey @pradeepjairamani, this is a known limitation. We require at least kernel 5.8 for the BPF recorder: https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/bpf-support.md

**Comment by pradeepjairamani** [comment]
Got it, thanks
