### ISSUE TITLE
Image build CI broken

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#1104]
#### What happened:

The CI for the jobs `image` and `ubi-image` are broken right now:
- https://github.com/kubernetes-sigs/security-profiles-operator/runs/7946447237?check_suite_focus=true
- https://github.com/kubernetes-sigs/security-profiles-operator/runs/7946447601?check_suite_focus=true

**Comment by JAORMX** [comment]
On it!

**Comment by saschagrunert** [comment]
Way better, but it still looks broken: https://github.com/kubernetes-sigs/security-profiles-operator/runs/7949099932?check_suite_focus=true
