### ISSUE TITLE
fail to record deployment pod

### ISSUE THREAD

**Issue by brness** [kubernetes-sigs/security-profiles-operator#1111]
#### What happened:
1. deploy a nginx deployment with label=nginx-pod
```
root@ubuntu:~/hml/profilerecording# kubectl get po -n demo -owide
NAME                         READY   STATUS    RESTARTS   AGE   IP             NODE             NOMINATED NODE   READINESS GATES
nginx-pod-5fdc6d77f-8f4bj    1/1     Running   0          10m   10.42.91.209   ubuntu-worker1   <none>           <none>
```
2.create a profilerecording with label=nginx-pod
```
root@ubuntu:~/hml/profilerecording# kubectl get profilerecording -n demo
NAME
my-recording
```
3.delete the pod and generate the seccompProfile
the bpf record logs:
```
Getting syscalls for profile my-recording-nginx-pod-0-1661245432"
I0823 09:09:21.203446  176791 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661245432" "try"=0
E0823 09:09:33.206934  176791 bpfrecorder.go:587] bpf-recorder "msg"="unable to find container ID in cluster, containerID: " "error"="find container ID: wait on retry: timed out waiting for the condition"  "66d965fdeaf367dc3ba340fa2a64401ab93d0f7dee7c1b64af893e694f7ec97f"=null
E0823 09:09:48.997315  176791 bpfrecorder.go:587] bpf-recorder "msg"="unable to find container ID in cluster, containerID: " "error"="find container ID: wait on retry: timed out waiting for the condition"  "66d965fdeaf367dc3ba340fa2a64401ab93d0f7dee7c1b64af893e694f7ec97f"=null
I0823 09:09:48.997370  176791 bpfrecorder.go:308] bpf-recorder "msg"="Got PIDs for the profile: [{id:320478 comm:nginx mntns:4026533007} {id:320491 comm:nginx mntns:4026533007} {id:320492 comm:nginx mntns:4026533007} {id:320493 comm:nginx mntns:4026533007} {id:320494 comm:nginx mntns:4026533007}]"
I0823 09:09:48.998518  176791 bpfrecorder.go:345] bpf-recorder "msg"="Cleaning up BPF hashmaps"
I0823 09:09:49.008765  176791 bpfrecorder.go:257] bpf-recorder "msg"="Not stopping because another recording is in progress"
```
and it did get the seccompProfile.

4.delete the generate pod but no seccompProfile found
bpf recorder logs:
```
Getting syscalls for profile my-recording-nginx-pod-0-1661245752"
I0823 09:16:43.754956  176791 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661245752" "try"=0
I0823 09:17:11.795790  176791 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661245752" "try"=1
```
pod can be deleted, but no seccompProfile found.

#### What you expected to happen:
the second pod can generate the secompProfile as well.

#### How to reproduce it (as minimally and precisely as possible):
the step is above, follow it.

#### Anything else we need to know?:
sometimes it just shows
```
I0823 11:19:01.632117 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:01.829289 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.029860 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.232930 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.434099 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.632431 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:02.833428 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.034221 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.235105 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.432070 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.631014 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:03.829859 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
I0823 11:19:04.031463 1100105 bpfrecorder.go:720] bpf-recorder "msg"="Found container ID in cluster"  "containerID"="f65311000e2f2b708e0d57d9199908b9c14884e77e2e5ec4d0cb4def6ba04323" "containerName"="calico-node"
```
and keeps shows and I can't see the useful infomation

#### Environment:

- Cloud provider or hardware configuration: 
-docker rancher v2.5.12
- OS (e.g: `cat /etc/os-release`): NAME
my-recording
root@ubuntu:~/hml/profilerecording# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel (e.g. `uname -a`):
 Linux ubuntu-master 5.11.5-051105-generic #202103091130 SMP Tue Mar 9 11:51:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Others:

**Comment by jhrozek** [comment]
You mentioned "the second pod can generate the secompProfile as well." but it's unclear to me which second pod..did the deployment have two replicas?

Could you check the annotations on the recorded pods after they've been admitted?

**Comment by brness** [comment]
my bad, no just one replica, because of the deployment, the newly generated pod would have the same label.
and I check the label of newly generated pod it did has the annotation
```
root@ubuntu:~/hml/profilerecording# kubectl describe po nginx-pod-5fdc6d77f-7jrrq -n demo
Name:         nginx-pod-5fdc6d77f-7jrrq
Namespace:    demo
Priority:     0
Node:         ubuntu-worker1/10.65.171.36
Start Time:   Tue, 23 Aug 2022 11:52:09 +0000
Labels:       app=nginx-pod
              pod-template-hash=5fdc6d77f
Annotations:  cni.projectcalico.org/podIP: 10.42.91.218/32
              cni.projectcalico.org/podIPs: 10.42.91.218/32
              io.containers.trace-bpf/nginx-pod: my-recording-nginx-pod-0-1661255529
Status:       Running
```
and here the profile name is  _my-recording-nginx-pod-0-1661255529_
after i delete this pod, the recorder logs shows:
```
Getting syscalls for profile my-recording-nginx-pod-0-1661255529"
I0823 11:54:59.249005 1571375 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661255529" "try"=0
I0823 11:54:59.261189 1571375 bpfrecorder.go:689] bpf-recorder "msg"="Container ID not yet available"  "containerName"="nginx-pod" "podName"="nginx-pod-5fdc6d77f-25lnl"
E0823 11:55:13.263699 1571375 bpfrecorder.go:587] bpf-recorder "msg"="unable to find container ID in cluster, containerID: " "error"="find container ID: wait on retry: timed out waiting for the condition"  "66d965fdeaf367dc3ba340fa2a64401ab93d0f7dee7c1b64af893e694f7ec97f"=null
E0823 11:55:29.066219 1571375 bpfrecorder.go:587] bpf-recorder "msg"="unable to find container ID in cluster, containerID: " "error"="find container ID: wait on retry: timed out waiting for the condition"  "66d965fdeaf367dc3ba340fa2a64401ab93d0f7dee7c1b64af893e694f7ec97f"=null
I0823 11:55:29.566697 1571375 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661255529" "try"=1
E0823 11:55:44.861579 1571375 bpfrecorder.go:587] bpf-recorder "msg"="unable to find container ID in cluster, containerID: " "error"="find container ID: wait on retry: timed out waiting for the condition"  "66d965fdeaf367dc3ba340fa2a64401ab93d0f7dee7c1b64af893e694f7ec97f"=null
I0823 11:55:59.254778 1571375 bpfrecorder.go:269] bpf-recorder "msg"="Getting syscalls for profile my-recording-nginx-pod-0-1661255529"
I0823 11:55:59.254813 1571375 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661255529" "try"=0
I0823 11:56:01.163666 1571375 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661255529" "try"=1
I0823 11:56:01.414089 1571375 bpfrecorder.go:285] bpf-recorder "msg"="Looking up PID for profile"  "profile"="my-recording-nginx-pod-0-1661255529" "try"=2
```

and I think this is because there was no event report to bpfrecorder.go. if there is event, the correct logs will be
```
I0823 11:49:35.074168 1571375 bpfrecorder.go:593] bpf-recorder "msg"="Saving PID for profile"  "mntns"=4026533007 "pid"=1575896 "profile"="my-recording-nginx-pod-0-1661255295"
I0823 11:49:35.074953 1571375 bpfrecorder.go:563] bpf-recorder "msg"="Using short path via tracked mount namespace"  "mntns"=4026533007 "pid"=1575909 "profile"="my-recording-nginx-pod-0-1661255295"
I0823 11:49:35.075054 1571375 bpfrecorder.go:563] bpf-recorder "msg"="Using short path via tracked mount namespace"  "mntns"=4026533007 "pid"=1575910 "profile"="my-recording-nginx-pod-0-1661255295"
I0823 11:49:35.075620 1571375 bpfrecorder.go:563] bpf-recorder "msg"="Using short path via tracked mount namespace"  "mntns"=4026533007 "pid"=1575911 "profile"="my-recording-nginx-pod-0-1661255295"
I0823 11:49:35.075674 1571375 bpfrecorder.go:563] bpf-recorder "msg"="Using short path via tracked mount namespace"  "mntns"=4026533007 "pid"=1575912 "profile"="my-recording-nginx-pod-0-1661255295"
```
which means the syscall is correctly reported

**Comment by brness** [comment]
So I wonder if this could because the same pid generated, so the recorder.bpf.o file can't send the event timely and store the pid to the old syscall map, BTW, why not delete the syscall map after generate the secompProfile but only the commands map? Maybe the possibility of the same pid is quite rare?

**Comment by brness** [comment]
during this problem, i find another strange situation.
```
I0823 12:39:17.178034 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178066 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178120 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178148 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178232 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178284 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178341 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178379 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178436 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178473 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178544 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178581 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178648 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178701 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.178757 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532445 "pid"=1915149
I0823 12:39:17.678518 1880140 bpfrecorder.go:554] bpf-recorder "msg"="current PID, and it's mount namespace"  "mntns"=4026532424 "pid"=1915220
```
the same pid of same mntns would process event to bpfrecorder many times. but this should not happen, is this my kernel problem?

**Comment by brness** [comment]
yes after i add the code 
```
	b.logger.Info("Cleaning up BPF hashmaps")
	for _, pid := range pids {
		b.loadUnloadMutex.Lock()
		if err := b.DeleteKey(b.comms, pid.id); err != nil {
			b.logger.Error(err, "unable to cleanup comms map", "pid", pid.id)
		}
		if err := b.DeleteKey(b.syscalls, pid.id); err != nil {
			b.logger.Error(err, "unable to cleanup syscall map", "pid", pid.id)
		}
		b.loadUnloadMutex.Unlock()
	}
```
I can delete po and generated the secompProfile, but the only problem is it will unload and upload bpf module more frequently. So if this is acceptable?

**Comment by brness** [comment]
> So I wonder if this could because the same pid generated, so the recorder.bpf.o file can't send the event timely and store the pid to the old syscall map, BTW, why not delete the syscall map after generate the secompProfile but only the commands map? Maybe the possibility of the same pid is quite rare? and i'm adding the delete syscall map to check if this is the problem..

no it still fail to generate the profile

**Comment by tshaiman** [comment]
same issue for me : 

E0827 12:15:19.314563    4186 bpfrecorder.go:580] bpf-recorder "msg"="unable to find container ID in cluster" "error"="find container ID: wait on retry: timed out waiting for the condition"
I0827 12:15:19.314712    4186 bpfrecorder.go:545] bpf-recorder "msg"="Skipping PID, because it's on the system mount namespace"  "mntns"=4026532797 "pid"=189737
I0827 12:15:19.315235    4186 bpfrecorder.go:545] bpf-recorder "msg"="Skipping PID, because it's on the system mount namespace"  "mntns"=4026532797 "pid"=189745
I0827 12:15:19.315676    4186 bpfrecorder.go:576] bpf-recorder "msg"="Found container for PID"  "containerID"="972cb40d5d9ccfd8dadb6da2bf97f1f0d828ed759a9ee009ab1f2ea45fb7fa7f" "pid"=1040
I0827 12:15:19.315834    4186 bpfrecorder.go:666] bpf-recorder "msg"="Looking up in-cluster container ID"  "id"="972cb40d5d9ccfd8dadb6da2bf97f1f0d828ed759a9ee009ab1f2ea45fb7fa7f" "try"=0


Cluster: Kind 1.24
profile verions : v0.4.3 ( v.0.4.4-dev was not found) 
Deploying the sample from the onboarding steps (nginx:1.19 workload)
SPOD is running correctly with 3 container and bpf-recorder container is available] 
Base OS Image for Kind is Ubuntu:22.04

**Comment by brness** [comment]
> 
have you encounter the situation that same pid would report many time until the pod run out of ressurce? just like my second issue? I'm not sure it only happen on me or a common issue?

**Comment by brness** [comment]
> 

have you encounter the situation that same pid would report many time until the pod run out of ressurce? just like my second issue? I'm not sure it only happen on me or a common issue?

**Comment by brness** [comment]
> same issue for me :
> 
> E0827 12:15:19.314563 4186 bpfrecorder.go:580] bpf-recorder "msg"="unable to find container ID in cluster" "error"="find container ID: wait on retry: timed out waiting for the condition" I0827 12:15:19.314712 4186 bpfrecorder.go:545] bpf-recorder "msg"="Skipping PID, because it's on the system mount namespace" "mntns"=4026532797 "pid"=189737 I0827 12:15:19.315235 4186 bpfrecorder.go:545] bpf-recorder "msg"="Skipping PID, because it's on the system mount namespace" "mntns"=4026532797 "pid"=189745 I0827 12:15:19.315676 4186 bpfrecorder.go:576] bpf-recorder "msg"="Found container for PID" "containerID"="972cb40d5d9ccfd8dadb6da2bf97f1f0d828ed759a9ee009ab1f2ea45fb7fa7f" "pid"=1040 I0827 12:15:19.315834 4186 bpfrecorder.go:666] bpf-recorder "msg"="Looking up in-cluster container ID" "id"="972cb40d5d9ccfd8dadb6da2bf97f1f0d828ed759a9ee009ab1f2ea45fb7fa7f" "try"=0
> 
> Cluster: Kind 1.24 profile verions : v0.4.3 ( v.0.4.4-dev was not found) Deploying the sample from the onboarding steps (nginx:1.19 workload) SPOD is running correctly with 3 container and bpf-recorder container is available] Base OS Image for Kind is Ubuntu:22.04

Hi Tomer, have you encounter the situation the same pid would report many times until the pod run out of resource?like I mentioned in the next line? I'm not sure it happen only on me or a common issue?

**Comment by brness** [comment]
Ok, Things are clear, It's because the mount of pid has reach the maximum capacity of the syscallMap, the default size of the map is 8*1024 and It can't be changed. @saschagrunert If there is a configurational way to adapt the value according to the real state. Or a easy way, change the type of syscall Map from BPF_MAP_TYPE_HASH to BPF_MAP_TYPE_LRU_HASH, this would help~~

**Comment by saschagrunert** [comment]
> change the type of syscall Map from BPF_MAP_TYPE_HASH to BPF_MAP_TYPE_LRU_HASH, this would help

This sounds great, thank you for digging into this! Do you mind proposing a PR for that?

**Comment by brness** [comment]
> > change the type of syscall Map from BPF_MAP_TYPE_HASH to BPF_MAP_TYPE_LRU_HASH, this would help
> 
> This sounds great, thank you for digging into this! Do you mind proposing a PR for that?

Sure
