### ISSUE TITLE
Make ebpf worker limit configurable

### ISSUE THREAD

**Issue by JAORMX** [kubernetes-sigs/security-profiles-operator#1122]
#### What would you like to be added:

We need a way to make the ebpf worker limit configurable. We don't necessarily want to make the parameter by itself configurable, but instead just have an intuitive way to adjust that based on a certain system's attributes. The idea is that it should be intuitive.

#### Why is this needed:

[A recent PR](https://github.com/kubernetes-sigs/security-profiles-operator/pull/1110) introduced parallelization of ebpf event processing. While this is a good performance enhancement, the number of "workers" (which is handled via a semaphore) is currently hard-coded to be `1000`. The intention is to allow folks with bigger machines (or smaller ones) to tune the parameter in order to better fit their environments. This has the caveat that tuning such a parameter can be very confusing for users, as folks will not know how to calculate an appropriate value, so we should be cautious in implementing this as intuitive as possible.

#### User story covered

* As an application developer, Ming would like to be able to automatically generate initial security profiles that are specific to the application.
* As an application SRE, Rajesh needs to be able to do long runs of a security profile in “complain-mode” to easily identify the impact of a profile being enforced without impacting the application.

**Comment by saschagrunert** [comment]
Totally agree that having a configuration makes sense here. What I also had in mind is either measuring or assuming that a goroutine uses a certain amount of memory. Then we could limit it by memory and adjust the resource spec accordingly to the value.

**Comment by JAORMX** [comment]
@saschagrunert I like the idea of measuring and basing the value on that.
