### ISSUE TITLE
Enable profilebinding using labels

### ISSUE THREAD

**Issue by pradeepjairamani** [kubernetes-sigs/security-profiles-operator#1136]
#### What would you like to be added:
Currently, profile binding feature can be used with image tags, can we can bind the profiles using labels?
#### Why is this needed:
Depending on the deployment configuration, image tags can change frequently , using labels from resources would make the profile binding easier

**Comment by saschagrunert** [comment]
I think this would be a valuable addition. We decided to use the image because it's the most simple way to achieve a binding. What do you think @pjbgf @jhrozek @JAORMX ?

**Comment by jhrozek** [comment]
I think this makes sense.

**Comment by JAORMX** [comment]
In principle it makes sense. My only concern is that most pods tend to have multiple containers, so we'd need more than a label to match where a profile should go. Else, the same profile would be applied in all containers and that might not be desirable.

**Comment by brness** [comment]
> In principle it makes sense. My only concern is that most pods tend to have multiple containers, so we'd need more than a label to match where a profile should go. Else, the same profile would be applied in all containers and that might not be desirable.

Maybe we can both use image and label to select the correct pod, and the image name to help to narrow the corresponding pod.

**Comment by pradeepjairamani** [comment]
Yes, there should be an option to enable profile binding for all the container images available within that specific label and  also remove/add image names in those labels as well, the problem with current implementation is image name changes frequently and to reduce operational overhead people will use a single profile for most of their application images

**Comment by pjbgf** [comment]
My concerns here would be on this being used to allow users with some cluster permissions to move a workload from a more strict security profile to a less strict one. It would be good to work out a few examples on how this would work, and what options would a platform admin have to limit malicious users (in a multi-tenant cluster for example) to use this to weaken workload enforcement.

Extending the current image-based approach to support regex/semver to enable users to define a range of image tags could potentially achieve similar results. Would that work for you?

**Comment by pradeepjairamani** [comment]
I am sure that would be useful but it will create more confusion for applying the profiles, I think having an option to select all or specific images in a label would be much more useful

**Comment by pjbgf** [comment]
@pradeepjairamani do you mind elaborating on "will create more confusion for applying the profiles" please?

Note that my concerns around using labels is that a Cluster admin will require the use of Admission Controllers / OPA to ensure users are not using it to weaken or bypass enforcement. Given that the primary goal of SPO is to deliver security profiles, and also be able to automatically bind them to public workloads (via ProfileBinding), I don't think it is worth extending it at the cost of making it less secure to other users - unless we find a way to implement that securely, which was my initial point.

What you are trying to achieve can be achieved with a mutating admission controller. You can continue to use SPO to deploy your profiles, and add a mutating admission controller (e.g. Kyverno) to set the workload policy based on matching conditions.

**Comment by pradeepjairamani** [comment]
got it, thanks @pjbgf

**Comment by jhrozek** [comment]
> @pradeepjairamani do you mind elaborating on "will create more confusion for applying the profiles" please?
> 
> Note that my concerns around using labels is that a Cluster admin will require the use of Admission Controllers / OPA to ensure users are not using it to weaken or bypass enforcement. Given that the primary goal of SPO is to deliver security profiles, and also be able to automatically bind them to public workloads (via ProfileBinding), I don't think it is worth extending it at the cost of making it less secure to other users - unless we find a way to implement that securely, which was my initial point.
> 
> What you are trying to achieve can be achieved with a mutating admission controller. You can continue to use SPO to deploy your profiles, and add a mutating admission controller (e.g. Kyverno) to set the workload policy based on matching conditions.

Reopening although I'm not sure if what I'm describind matches the original issue, maybe it would be worth opening a new one?

What if we extended the binding CR to also contain a label selector, if the label selector was set AND matching an object AND matching the image, then the bind would happen?

What I'm looking to solve is: We maintain an operator that uses a single image to accomplish several tasks, so the image is called with different arguments. Each workload, in addition to different arguments also has different labels. So I was thinking that we could have multiple binding CRs in a single namespace, with different label selectors that would be used to bind different policies based on the labels of the workloads.

Does that sound sane?

**Comment by JAORMX** [comment]
@jhrozek let's expand the use-case a little bit more and see where we could improve. Do you really want to use the same SELinux profile for all containers in one pod? I would have thought that three different sub-programs in the container would have different SELinux profiles as needed. It would then be more relevant to match a profile to a container in a pod.

**Comment by pjbgf** [comment]
@jhrozek combining matched image and labels does sound good.

@JAORMX for of a question, on SELinux is it not possible to get the profile to have "sub-profiles" that are targeted to specific binaries?

**Comment by JAORMX** [comment]
@pjbgf It's not possible with the current SELinux implementation. It would be possible, but it would complicate the SELinux profile implementation, and I don't quite see much benefit for this. I'd much rather label profiles to mark they belong to the same pod or app.
