### ISSUE TITLE
Unable to delete seccompprofile if one of node is deleted

### ISSUE THREAD

**Issue by kecebon9** [kubernetes-sigs/security-profiles-operator#1152]
#### What happened:

Unable to delete the seccompprofiles if one of the node deleted/updated because of the finalizers is not updated with the latest nodes. I'm not sure if this bug or as per design.
Thank you

#### What you expected to happen:

Possible if SPO update seccompprofiles on the Finalizers part to the latest k8s nodes?

#### How to reproduce it (as minimally and precisely as possible):

- Start minikube with 3 nodes
```$ minikube  start --kubernetes-version=v1.21.14 --nodes=3 --memory 4000 --cpus```
- Install SPO
- Check the default SeccomProfiles, there are 3 finalizers
```
$ kubectl get seccompprofiles -n security-profiles-operator log-enricher-trace -o json | jq .metadata.finalizers
[
            "minikube-m03-delete",
            "minikube-m02-delete",
            "minikube-delete"
]
```
- Delete one of the node
```
$ minikube node delete minikube-m03
```
- The SeccompProfiles still have `minikube-m03` as finalizers
```
$ kubectl get seccompprofiles -n security-profiles-operator log-enricher-trace -o json | jq .metadata.finalizers
[
            "minikube-m03-delete",
            "minikube-m02-delete",
            "minikube-delete"
]
```
- I can't delete the seccompprofiles because the `"minikube-m03-delete"` is still exist (the old node that already deleted), unless if i patch it the finalizers like:
```
$ kubectl patch seccompprofiles log-enricher-trace -n security-profiles-operator -p '{"metadata":{"finalizers":[]}}' --type=merge
```

#### Anything else we need to know?:

I observed this on our Amazon EKS cluster, but for this testing i tested it on minikube with the same behavior. On our Amazon EKS clusters we have patching cycle that will delete the old node and bring up the new node (with new latest image). So after the patching the finalizers on the seccompprofiles still showing the old nodes, this make we can't delete the seccompprofles.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
This feels like a bug, thank you for reporting that!
