### ISSUE TITLE
Expand the scope of the operator to AppArmor

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#118]
Loading AppArmor profiles could be done easily by the operator, too. We probably have to rename the project to something like "security-operator", too.

**Comment by saschagrunert** [comment]
cc @mrostecki

**Comment by hasheddan** [comment]
@saschagrunert @pjbgf what are y'all thinking about potential rename? Would likely be good to do sooner rather than later if it is something we want to do.

**Comment by saschagrunert** [comment]
> @saschagrunert @pjbgf what are y'all thinking about potential rename? Would likely be good to do sooner rather than later if it is something we want to do.

Yes I think that's a good idea. Do you wanna go ahead and create the issue? :+1:

**Comment by pjbgf** [comment]
Yep, completely agree we rather do that soon. Will create a few issues on this now.

**Comment by pjbgf** [comment]
Initial support done via #680
