### ISSUE TITLE
When recording, too many pids are generated in the container and the ebpf map is full

### ISSUE THREAD

**Issue by neblen** [kubernetes-sigs/security-profiles-operator#1188]
#### What happened:
When recording, too many pids are generated in the container and the ebpf map is full.Mainly because the syscalls map is full, resulting in missing recorded syscalls.This happens when a node records multiple pods at the same time

#### What you expected to happen:
The ebpf map will not be full when recording syscall
#### How to reproduce it (as minimally and precisely as possible):
1.Multi-node k8s cluster 2. profilerecording runs continuously
#### Anything else we need to know?:
1.At present, the mapping relationship of syscall map is that pid corresponds to syscall.
2.In fact, the most reasonable mapping relationship for syscall map should be mntns corresponding to syscall
#### Environment:
K8s version:v1.20.10
OS-IMAGE:Ubuntu 20.04.3 LT
KERNEL-VERSION:5.15.0-46-generic
CONTAINER-RUNTIME:docker://20.10.7
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by neblen** [comment]
There is currently a solution to change the syscall map mapping relationship to mntns corresponding to syscall.In fact, the user mode does not need to record the pid list corresponding to the profile.The user mode profile only needs to record the mntns corresponding to the profile.

**Comment by saschagrunert** [comment]
@neblen thank you for the report, do you plan to give a PR a try for a fix?

**Comment by neblen** [comment]
> @neblen thank you for the report, do you plan to provide a PR for a fix?

yes，i want to fix this. At present, the code part of using mntns to save syscall has been written and still being tested.
