### ISSUE TITLE
Use helm-docs to auto-generate helm documentation

### ISSUE THREAD

**Issue by tylerauerbeck** [kubernetes-sigs/security-profiles-operator#1194]
#### What would you like to be added:
The user experience for those installing SPO via the helm chart could be improved by using a tool like https://github.com/norwoodj/helm-docs to auto-generate documentation around the values available to the helm-chart.

#### Why is this needed:

Currently, a user would need to dig through both the values file and the templates themselves to discover what settings are available to the helm chart.

#### User story covered

As a User
I would like to be able to easily discover available SPO settings in the helm chart
so that I could deploy SPO with an appropriate configuration

**Comment by saschagrunert** [comment]
Awesome, thank you so much @chenliu1993!
