### ISSUE TITLE
Some operator pods fail to initialize because metrics-cert-volume failed to mount

### ISSUE THREAD

**Issue by rhmdnd** [kubernetes-sigs/security-profiles-operator#1197]
#### What happened:

The operator pods failed to initialize during the installation process.

#### What you expected to happen:

I expected the operator pods to come up and be available after installing.

#### How to reproduce it (as minimally and precisely as possible):

To install, I logged into the cluster via CLI, then used the `make deploy-openshift-dev` Makefile target.

```
$ oc login --token=$TOKEN --server=$SERVER_ENDPOINT
$ make deploy-openshift-dev
```

Checking the pods show:

```$ oc get pods -n security-profiles-operator                                                                                                                                                             130 ↵
NAME                                                 READY   STATUS     RESTARTS      AGE
security-profiles-operator-7cc5dd49f9-hjrs6          1/1     Running    2 (14m ago)   78m
security-profiles-operator-7cc5dd49f9-pc9wk          1/1     Running    3 (12m ago)   78m
security-profiles-operator-7cc5dd49f9-vvk7k          1/1     Running    1 (40m ago)   78m
security-profiles-operator-webhook-d9f9c846b-4792b   1/1     Running    4 (14m ago)   78m
security-profiles-operator-webhook-d9f9c846b-h76d6   1/1     Running    3 (21m ago)   78m
security-profiles-operator-webhook-d9f9c846b-xb8hn   1/1     Running    1 (40m ago)   78m
spod-588pb                                           0/3     Init:0/2   0             78m
spod-8skcf                                           0/3     Init:0/2   0             78m
spod-8tql8                                           0/3     Init:0/2   0             78m
spod-d9b7c                                           0/3     Init:0/2   0             78m
spod-h2rtk                                           0/3     Init:0/2   0             78m
spod-s6l5j                                           0/3     Init:0/2   0             78m
```

Describing the pod for more details shows:

```
 $ oc describe pod spod-d9b7c -n security-profiles-operator
...
Warning  FailedMount  3m17s (x31 over 58m)  kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[metrics-cert-volume], unattached volumes=[kube-api-access-bfnq9 profile-recording-output-volume grpc-server-volume operator-profiles-volume host-fsselinux-volume host-etcselinux-volume host-operator-volume selinuxd-private-volume host-varlib-volume selinux-drop-dir host-varlibselinux-volume metrics-cert-volume]: timed out waiting for the condition
```

I can confirm that the secret is indeed missing:

```
$ oc get secrets metrics-cert-volume
Error from server (NotFound): secrets "metrics-cert-volume" not found
```

#### Environment:

- Cloud provider or hardware configuration: I'm using OpenShift on OpenStack
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:
- Kubernetes Version: v1.24.0+8c7c967

**Comment by jhrozek** [comment]
Thanks for the bug report!

I wonder if this was an issue with that particular cluster or a bug in OpenShift because:
 - if the service hadn't been created, we should have seen some evidence coming from https://github.com/kubernetes-sigs/security-profiles-operator/blob/5a5d8bc96b4bb0029f54c237f8354da9f77886f9/internal/pkg/manager/spod/spod_controller.go#L328 and the operator would probably end in a `CrashLoopBackOff`
 - the service should be annotated with `service.beta.openshift.io/serving-cert-secret-name=metrics-server-cert` which should cause OpenShift to generate the secret..

I think at this point we need to wait and see if we can reproduce again..
