### ISSUE TITLE
AppArmor profiles not loading on worker nodes in K8S cluster

### ISSUE THREAD

**Issue by juggarnautss** [kubernetes-sigs/security-profiles-operator#1210]
#### What happened:
We are using using AppArmor in our project.
In K8S cluster, After installing the SPO and enabing the AppArmor feature, i am creating the AppArmor profiles ,profiles are created successfully however those profiles are not getting loaded in the worker nodes.

#### What you expected to happen:
Once i create the AppArmor profiles, the profiles should get loaded in all the worker nodes so that whenever i launch any application pod on worker nodes , application should get validated by the profiles before doing any system operations.

#### How to reproduce it (as minimally and precisely as possible):

Configuration: VMs, 1 master and 1 worker

Enbled AppArmor on both the VM's
```
kmaster@kmaster:~$ kubectl get nodes -o=jsonpath='{range .items[*]}{@.metadata.name}: {.status.conditions[?(@.reason=="KubeletReady")].message}{"\n"}{end}'
kmaster: kubelet is posting ready status. AppArmor enabled
kworker1: kubelet is posting ready status. AppArmor enabled
```

Installed SPO:
SPO : v10.4.3
```
$ kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
$ kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/deploy/operator.yaml
```

Enabled AppArmor:
kmaster@kmaster:~/testProfiles/installFiles/UsingSPO$ cat config.yaml
```
---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SecurityProfilesOperatorDaemon
metadata:
  name: spod
  namespace: security-profiles-operator
spec:
  selinuxTypeTag: ""
  enableSelinux: false
  enableLogEnricher: false
  verbosity: 1
  enableAppArmor: true
```

Profile creation:
```
---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  name: apparmorprofile-test100
  annotations:
    description: Block writing to any files in the disk.
spec:
  policy: |
    #include <tunables/global>

    profile test-profile flags=(attach_disconnected) {
      #include <abstractions/base>

      file,

      # Deny all file writes.
      deny /** w,
    }
```

Once i apply the profile, follwoign errors are coming in the SPOD and Security profile Operator pod logs:
spod log message:
```
I0928 20:36:35.539155   45582 apparmorprofile.go:112] apparmor-spod "msg"="Reconciling AppArmorProfile" "apparmorprofile"="apparmorprofile-test100" "namespace"="security-profiles-operator"
E0928 20:36:35.539312   45582 apparmorprofile.go:180] apparmor-spod "msg"="cannot load profile into node" "error"="open /etc/apparmor.d/spo-apparmorprofile-test100: no such file or directory" "apparmorprofile"="apparmorprofile-test100" "namespace"="security-profiles-operator"
E0928 20:36:35.539351   45582 controller.go:326]  "msg"="Reconciler error" "error"="cannot load profile into node: open /etc/apparmor.d/spo-apparmorprofile-test100: no such file or directory" "appArmorProfile"={"name":"apparmorprofile-test100","namespace":"security-profiles-operator"} "controller"="apparmorprofile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="AppArmorProfile" "name"="apparmorprofile-test100" "namespace"="security-profiles-operator" "reconcileID"="5a0bd06a-4274-4b15-8f47-fe92b09f354d"
```

security-profiles-operator pod message:
```
E0928 20:40:06.667191       1 controller.go:326]  "msg"="Reconciler error" "error"="getting owner profile: the node status owner is of an unknown kind" "controller"="nodestatus" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="SecurityProfileNodeStatus" "name"="apparmorprofile-test100-kworker1" "namespace"="security-profiles-operator" "reconcileID"="b316d16e-52a0-4857-870f-a0fc78c079c1" "securityProfileNodeStatus"={"name":"apparmorprofile-test100-kworker1","namespace":"security-profiles-operator"}
I0928 20:40:13.569728       1 ca.go:62] spod-config "msg"="Using cert-manager as certificate provider"
```

#### Anything else we need to know?:

Also, i wanted to know how to unload a AppArmor profiles , once the loading is successful.

#### Environment:

- Cloud provider or hardware configuration: 
Using VBOX VM's on my local laptop

- OS (e.g: `cat /etc/os-release`):
kmaster@kmaster:~/testProfiles/installFiles/UsingSPO$ cat /etc/os-release
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

- Kernel (e.g. `uname -a`):
kmaster@kmaster:~/testProfiles/installFiles/UsingSPO$ uname -a
`Linux kmaster 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

- Others:

**Comment by juggarnautss** [comment]
Analysis so far:

Once i apply the profile, follwoign errors are coming in the SPOD and Security profile Operator pod logs:
spod log message:
```
I0928 20:36:35.539155   45582 apparmorprofile.go:112] apparmor-spod "msg"="Reconciling AppArmorProfile" "apparmorprofile"="apparmorprofile-test100" "namespace"="security-profiles-operator"
E0928 20:36:35.539312   45582 apparmorprofile.go:180] apparmor-spod "msg"="cannot load profile into node" "error"="open /etc/apparmor.d/spo-apparmorprofile-test100: no such file or directory" "apparmorprofile"="apparmorprofile-test100" "namespace"="security-profiles-operator"
E0928 20:36:35.539351   45582 controller.go:326]  "msg"="Reconciler error" "error"="cannot load profile into node: open /etc/apparmor.d/spo-apparmorprofile-test100: no such file or directory" "appArmorProfile"={"name":"apparmorprofile-test100","namespace":"security-profiles-operator"} "controller"="apparmorprofile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="AppArmorProfile" "name"="apparmorprofile-test100" "namespace"="security-profiles-operator" "reconcileID"="5a0bd06a-4274-4b15-8f47-fe92b09f354d"
```


security-profiles-operator pod message:
```
E0928 20:40:06.667191       1 controller.go:326]  "msg"="Reconciler error" "**error"="getting owner profile: the node status owner is of an unknown kind"** "controller"="nodestatus" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="SecurityProfileNodeStatus" "name"="apparmorprofile-test100-kworker1" "namespace"="security-profiles-operator" "reconcileID"="b316d16e-52a0-4857-870f-a0fc78c079c1" "securityProfileNodeStatus"={"name":"apparmorprofile-test100-kworker1","namespace":"security-profiles-operator"}
I0928 20:40:13.569728       1 ca.go:62] spod-config "msg"="Using cert-manager as certificate provider"
```

After tracing the error, i found the follwing file where there is no AppArmor case in nodestatus.go

File Name : SecurityProfileOperator\security-profiles-operator-main\security-profiles-operator-main\internal\pkg\manager\nodestatus\nodestatus.go.
Let me know, if the finding is correct or not.

 
```
func (r *StatusReconciler) getProfileFromStatus(
    ctx context.Context,
    s *statusv1alpha1.SecurityProfileNodeStatus,
) (pbv1alpha1.StatusBaseUser, error) {
    ctrl := metav1.GetControllerOf(s)
    if ctrl == nil

{         return nil, fmt.Errorf("getting owner profile: %w", ErrNoOwnerProfile)     }
 
    key := types.NamespacedName

{         Name:      ctrl.Name,         Namespace: s.GetNamespace(),     }
    var prof pbv1alpha1.StatusBaseUser
    switch ctrl.Kind {
    case "SeccompProfile":
        prof = &seccompprofileapi.SeccompProfile{}
    case "SelinuxProfile":
        prof = &selxv1alpha2.SelinuxProfile{}
  // No case for AppArmor exist
    default:
        return nil, fmt.Errorf("getting owner profile: %w", ErrUnkownOwnerKind)
    }
    if err := r.client.Get(ctx, key, prof); err != nil

{         return nil, fmt.Errorf("getting owner profile: %s/%s: %w", s.GetNamespace(), ctrl.Name, err)     }
    return prof, nil
}
```

**Comment by juggarnautss** [comment]
@All : Anybody help me with this info whether AppArmor profiles loading/unloading working on worker nodes in K8S cluster ?

**Comment by pjbgf** [comment]
@juggarnautss thanks for reporting this. AppArmor is indeed WIP and should have documentation and reliability improvements soon - once https://github.com/kubernetes-sigs/security-profiles-operator/pull/1063 is merged.

Can you please confirm if you are getting the messages below in the logs from your spod?
```
I1103 22:29:05.349882    9680 apparmorprofile.go:277] apparmor-spod "msg"="detecting apparmor support..." 
I1103 22:29:05.350128    9680 apparmorprofile.go:284] apparmor-spod "msg"="apparmor enabled: OK" 
I1103 22:29:05.350167    9680 apparmorprofile.go:287] apparmor-spod "msg"="apparmor enforceable: OK" 
```
That should confirm that the SPO can detect apparmor capabilities.

Can you also share the output when executing the commands below directly into one of your nodes:
```
cat /sys/module/apparmor/parameters/enabled
ls -la /etc/apparmor.d
aa-status
```

**Comment by juggarnautss** [comment]
> @juggarnautss thanks for reporting this. AppArmor is indeed WIP and should have documentation and reliability improvements soon - once #1063 is merged.
> 
> Can you please confirm if you are getting the messages below in the logs from your spod?
> 
> ```
> I1103 22:29:05.349882    9680 apparmorprofile.go:277] apparmor-spod "msg"="detecting apparmor support..." 
> I1103 22:29:05.350128    9680 apparmorprofile.go:284] apparmor-spod "msg"="apparmor enabled: OK" 
> I1103 22:29:05.350167    9680 apparmorprofile.go:287] apparmor-spod "msg"="apparmor enforceable: OK" 
> ```
> 
> That should confirm that the SPO can detect apparmor capabilities.
> 
> Can you also share the output when executing the commands below directly into one of your nodes:
> 
> ```
> cat /sys/module/apparmor/parameters/enabled
> ls -la /etc/apparmor.d
> aa-status
> ```

@pjbgf : Thank you for reverting on this.

Please clarify which version of operator.yaml shall i use for testing with image quay.io/paulinhu/security-profiles-operator:aa-fix .
I have tried with v0.5.0 operator.yaml but its breaking. please help me on this.

**Comment by pjbgf** [comment]
You should be able to use that image with the `operator.yaml` for `v0.5.0`. Did you confirm that your `SecurityProfilesOperatorDaemon` was created and `enableAppArmor` was enabled?

Is there any other errors you observed you could share?

**Comment by juggarnautss** [comment]
@pjbgf 
Hi Paulo,

Took the latest SPO release where the app-armor fix is merged. Also, found that SPO installation manual is updated with AppArmor related data.
Therefore have done one round of testing with latest code and patch the spod with enabling apparmor.

FINDING:
After enabling apparmor,  found that the apparmor is enabled by SPO by checking the logs but SPODS are still restarting and ultimately CrashLoopBackOff is happening.

Please help us in stabilizing the SPOD restart and crashes. Also let me know if any addtional data is required for RCA.

**Logs for AppArmor enable in SPOD: $kubectl logs spod-vk79p -n security-profiles-operator**
```
I1114 16:33:00.739913   59021 profilerecorder.go:141] recorder-spod "msg"="Setting up profile recorder" "Node"="192.168.29.40"
**I1114 16:33:00.740421   59021 apparmorprofile.go:277] apparmor-spod "msg"="detecting apparmor support..."
I1114 16:33:00.741436   59021 apparmorprofile.go:284] apparmor-spod "msg"="apparmor enabled: OK"
I1114 16:33:00.741596   59021 apparmorprofile.go:287] apparmor-spod "msg"="apparmor enforceable: OK"**
I1114 16:33:00.742566   59021 main.go:451] setup "msg"="starting daemon"
I1114 16:33:00.743334   59021 internal.go:366]  "msg"="Starting server" "addr"={"IP":"::","Port":8085,"Zone":""} "kind"="health probe"
I1114 16:33:00.743536   59021 internal.go:366]  "msg"="Starting server" "addr"={"IP":"::","Port":8080,"Zone":""} "kind"="metrics" "path"="/metrics"
I1114 16:33:00.744434   59021 controller.go:185]  "msg"="Starting EventSource" "controller"="apparmorprofile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="AppArmorProfile" "source"="kind source: *v1alpha1.AppArmorProfile"
I1114 16:33:00.744589   59021 controller.go:193]  "msg"="Starting Controller" "controller"="apparmorprofile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="AppArmorProfile"
```

**Logs for CrashLoopBackOff :  $kubectl logs spod-vk79p -n security-profiles-operator**
```
E1114 16:28:10.164918   56286 source.go:139] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"SeccompProfile\" in version \"security-profiles-operator.x-k8s.io/v1beta1\"" "kind"={"Group":"security-profiles-operator.x-k8s.io","Kind":"SeccompProfile"}
I1114 16:28:10.164952   56286 controller.go:227]  "msg"="Starting workers" "controller"="profilerecorder" "controllerGroup"="" "controllerKind"="Pod" "worker count"=1
I1114 16:28:10.164974   56286 controller.go:227]  "msg"="Starting workers" "controller"="apparmorprofile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="AppArmorProfile" "worker count"=1
E1114 16:28:20.540268   56286 source.go:139] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"SeccompProfile\" in version \"security-profiles-operator.x-k8s.io/v1beta1\"" "kind"={"Group":"security-profiles-operator.x-k8s.io","Kind":"SeccompProfile"}
E1114 16:28:30.523650   56286 source.go:139] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"SeccompProfile\" in version \"security-profiles-operator.x-k8s.io/v1beta1\"" "kind"={"Group":"security-profiles-operator.x-k8s.io","Kind":"SeccompProfile"}
E1114 16:35:00.748138   59021 controller.go:210]  "msg"="Could not wait for Cache to sync" "error"="failed to wait for profile caches to sync: timed out waiting for cache to be synced" "controller"="profile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="SeccompProfile"
I1114 16:35:00.748266   59021 internal.go:571]  "msg"="Stopping and waiting for non leader election runnables"
I1114 16:35:00.748292   59021 internal.go:575]  "msg"="Stopping and waiting for leader election runnables"
I1114 16:35:00.748352   59021 controller.go:247]  "msg"="Shutdown signal received, waiting for all workers to finish" "controller"="apparmorprofile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="AppArmorProfile"
I1114 16:35:00.748427   59021 controller.go:247]  "msg"="Shutdown signal received, waiting for all workers to finish" "controller"="profilerecorder" "controllerGroup"="" "controllerKind"="Pod"
I1114 16:35:00.748481   59021 controller.go:249]  "msg"="All workers finished" "controller"="apparmorprofile" "controllerGroup"="security-profiles-operator.x-k8s.io" "controllerKind"="AppArmorProfile"
I1114 16:35:00.748514   59021 controller.go:249]  "msg"="All workers finished" "controller"="profilerecorder" "controllerGroup"="" "controllerKind"="Pod"
I1114 16:35:00.748533   59021 internal.go:581]  "msg"="Stopping and waiting for caches"
I1114 16:35:00.748933   59021 internal.go:585]  "msg"="Stopping and waiting for webhooks"
I1114 16:35:00.748954   59021 internal.go:589]  "msg"="Wait completed, proceeding to shutdown the manager"
**E1114 16:35:00.748985   59021 main.go:229] setup "msg"="running security-profiles-operator" "error"="SPOd error: failed to wait for profile caches to sync: timed out waiting for cache to be synced"Some text with a title**
```

Alos, please find below command output from worker nodes as suggested:

kworker1@kworker1:~$ cat /sys/module/apparmor/parameters/enabledcat /sys/module/apparmor/parameters/enabled
cat: /sys/module/apparmor/parameters/enabledcat: No such file or directory
Y
kworker1@kworker1:~$ cat /sys/module/apparmor/parameters/enabled
Y
kworker1@kworker1:~$ ls -la /etc/apparmor.d
total 104
drwxr-xr-x   8 root root  4096 Oct 17 20:01 .
drwxr-xr-x 104 root root  4096 Nov 12 06:28 ..
drwxr-xr-x   2 root root  4096 Aug  9 11:57 abi
drwxr-xr-x   4 root root  4096 Oct 17 20:01 abstractions
drwxr-xr-x   2 root root  4096 Oct 17 19:45 disable
drwxr-xr-x   2 root root  4096 Jun 21 04:46 force-complain
drwxr-xr-x   2 root root  4096 Oct 17 20:01 local
-rw-r--r--   1 root root  1339 Jun 21 04:46 lsb_release
-rw-r--r--   1 root root  1189 Jun 21 04:46 nvidia_modprobe
-rw-r--r--   1 root root  3461 Jun 21 10:38 sbin.dhclient
drwxr-xr-x   5 root root  4096 Aug  9 11:57 tunables
-rw-r--r--   1 root root  1446 Jun  9  2021 usr.bin.irssi
-rw-r--r--   1 root root  3448 Mar 17  2022 usr.bin.man
-rw-r--r--   1 root root  2561 Jun  9  2021 usr.bin.pidgin
-rw-r--r--   1 root root  1421 Jun 20  2021 usr.bin.tcpdump
-rw-r--r--   1 root root  1820 Jun  9  2021 usr.bin.totem
-rw-r--r--   1 root root  1220 Jun  9  2021 usr.bin.totem-previewers
-rw-r--r--   1 root root 28376 Aug  8 09:17 usr.lib.snapd.snap-confine.real
-rw-r--r--   1 root root  1060 Jun  9  2021 usr.sbin.apt-cacher-ng
-rw-r--r--   1 root root  1592 Nov 16  2021 usr.sbin.rsyslogd
kworker1@kworker1:~$ sudo aa-status
apparmor module is loaded.
40 profiles are loaded.
39 profiles are in enforce mode.
   /snap/snapd/17029/usr/lib/snapd/snap-confine
   /snap/snapd/17029/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /snap/snapd/17336/usr/lib/snapd/snap-confine
   /snap/snapd/17336/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/bin/man
   /usr/bin/pidgin
   /usr/bin/pidgin//sanitized_helper
   /usr/bin/totem
   /usr/bin/totem-audio-preview
   /usr/bin/totem-video-thumbnailer
   /usr/bin/totem//sanitized_helper
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /{,usr/}sbin/dhclient
   apt-cacher-ng
   cri-containerd.apparmor.d
   lsb_release
   man_filter
   man_groff
   nvidia_modprobe
   nvidia_modprobe//kmod
   snap-update-ns.lxd
   snap.lxd.activate
   snap.lxd.benchmark
   snap.lxd.buginfo
   snap.lxd.check-kernel
   snap.lxd.daemon
   snap.lxd.hook.configure
   snap.lxd.hook.install
   snap.lxd.hook.remove
   snap.lxd.lxc
   snap.lxd.lxc-to-lxd
   snap.lxd.lxd
   snap.lxd.migrate
   snap.lxd.user-daemon
   tcpdump
1 profiles are in complain mode.
   /usr/bin/irssi
0 profiles are in kill mode.
0 profiles are in unconfined mode.
15 processes have profiles defined.
15 processes are in enforce mode.
   /usr/sbin/nginx (1007) cri-containerd.apparmor.d
   /usr/sbin/nginx (1035) cri-containerd.apparmor.d
   /usr/sbin/nginx (1036) cri-containerd.apparmor.d
   /app/cmd/controller/controller (2387) cri-containerd.apparmor.d
   /app/cmd/webhook/webhook (2544) cri-containerd.apparmor.d
   /coredns (2668) cri-containerd.apparmor.d
   /cluster-proportional-autoscaler (2861) cri-containerd.apparmor.d
   /app/cmd/cainjector/cainjector (2909) cri-containerd.apparmor.d
   /security-profiles-operator (50423) cri-containerd.apparmor.d
   /security-profiles-operator (50464) cri-containerd.apparmor.d
   /security-profiles-operator (50583) cri-containerd.apparmor.d
   /security-profiles-operator (51169) cri-containerd.apparmor.d
   /security-profiles-operator (51292) cri-containerd.apparmor.d
   /security-profiles-operator (51393) cri-containerd.apparmor.d
   /usr/local/bin/kube-rbac-proxy (55064) cri-containerd.apparmor.d
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
0 processes are in mixed mode.
0 processes are in kill mode.

**Comment by pjbgf** [comment]
I have noticed some issues due to the default `spod` settings.
Can you please try again with the below after removing all the operator objects from the cluster (operator, namespace, CRDs, etc)?

Here I deploy latest from main, delete spod, create a new one and deploy the sample profile:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/deploy/operator.yaml

kubectl -n security-profiles-operator delete spod spod

kubectl apply -f - <<EOF
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SecurityProfilesOperatorDaemon
metadata:
  labels:
    app: security-profiles-operator
  name: spod
  namespace: security-profiles-operator
spec:
  enableAppArmor: true
EOF

kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/examples/apparmorprofile.yaml
```

In a few seconds you should be able to see:
```
$ kubectl logs -n security-profiles-operator -l name=spod -c security-profiles-operator | grep test-profile
I1115 23:41:50.824401   30631 apparmorprofile.go:108] apparmor-spod "msg"="Reconciling AppArmorProfile" "apparmorprofile"="test-profile" "namespace"="default"
I1115 23:41:50.851329   30631 apparmorprofile.go:192] apparmor-spod "msg"="Already in the expected Installed state" "apparmorprofile"="test-profile" "namespace"="default"
```

**Comment by pjbgf** [comment]
@juggarnautss we have released a version Today which means the official operator image is out with the necessary fixes for AppArmor to work.

I will try to invest some time on the settings later on this week. That isn't a fix as such, but rather a sensible default that would not give users the impression of the operator not working.

As for the chart, it is based in dir `/deploy/helm` of this repo. At the moment, we don't expose an `enableAppArmor` attribute. So feel free to propose a PR for it, otherwise I will try to get around to it at some point this week.

**Comment by tuxerrante** [comment]
Thanks!
@pjbgf does that mean that _[release 0.6](https://github.com/kubernetes-sigs/security-profiles-operator/releases/tag/v0.6.0)_ solve this issue even if not officially mentioned in the release notes?

**Comment by juggarnautss** [comment]
@pjbgf 

Thank you Paulo for addressing my queries.

I will raise the required PR on enabling apparmor by default via helm.

**Comment by juggarnautss** [comment]
@pjbgf 

Hi Paulo,

I have raised the feature required to enable apparmor by default.
https://github.com/kubernetes-sigs/security-profiles-operator/issues/1320

Thanks and regards,
Sirin

**Comment by rahulroshank** [comment]
Hi Paulo,

Tried deploying SPO using helm chart from 0.6.0 release. 
Observed SPO image version tagged to latest. Are we going to keep it to latest or change it to 0.6.0?

**Comment by pjbgf** [comment]
@tuxerrante that's correct, I have now rectified the release notes to include the PR that fixes this.

**Comment by pjbgf** [comment]
@rahulroshank I created an issue (https://github.com/kubernetes-sigs/security-profiles-operator/issues/1334) to track making that configurable.

Given that we are always patching and evolving the operator, you may want to still use the `latest` tag, however I understand that for hermetic deployments (and also in highly regulated environment), you may want to stick to immutable tags instead.

**Comment by juggarnautss** [comment]
SPO is currently stable with AppArmor enabled. Also the profiles are getting loaded and unloaded properly across worker nodes.
Hence, marking this issue as closed.
