### ISSUE TITLE
Can we install security-profiles-operator without cert-manager

### ISSUE THREAD

**Issue by pradeepjairamani** [kubernetes-sigs/security-profiles-operator#1226]
#### What would you like to be added:
Wanted to understand if there's a way we can remove dependency for cert-manager?

**Comment by saschagrunert** [comment]
Hey @pradeepjairamani, thank you for the request. Right now we require cert-manager for creating certificates during the deployment of the operator, for example to make the webhook work. We also support OpenShift which does not require cert-manager at all because it has it's own CA injector.

**Comment by pradeepjairamani** [comment]
Is there any way we can manually install certificate for mutating webhook? I have a strong requirement for not keeping cert-manager as a dependency in the environment

**Comment by saschagrunert** [comment]
We would have to make that configurable, but technically it should work, yes.

**Comment by pradeepjairamani** [comment]
can you please help me with a few pointers on where to look at for making this configurable
