### ISSUE TITLE
Rename operator to consider support to other security capabilities (i.e. AppArmor)

### ISSUE THREAD

**Issue by pjbgf** [kubernetes-sigs/security-profiles-operator#127]
It may be worth renaming the operator given the direction of broaden up its capabilities. (xref https://github.com/kubernetes-sigs/seccomp-operator/issues/118)

My personal suggestion would be "security-profiles-operator".

Places to rename:
- [x] repository https://github.com/kubernetes/org/issues/2177
- [x] code base https://github.com/kubernetes-sigs/security-profiles-operator/pull/139
- [x] slack channel https://github.com/kubernetes/community/pull/5098

/priority important-soon

**Comment by pjbgf** [comment]
Changed the suggested name to `security-profiles-operator`. Will present it to sig-node next week.

**Comment by saschagrunert** [comment]
> Changed the suggested name to `security-profiles-operator`. Will present it to sig-node next week.

Thank you for taking care of that! :pray: 

+1 for the name

**Comment by dchen1107** [comment]
+1 on the new name: security-profiles-operator

**Comment by mrunalp** [comment]
:+1:

**Comment by saschagrunert** [comment]
That's now done
/close
