### ISSUE TITLE
Easier handling of default runtime profiles

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#1313]
#### What would you like to be added:
At the very least, create the default runtime profiles which are supposed to be reused through the `baseProfileName` in the SPO namespace. We could `go:embed` them from the example manifests and create on startup.

But maybe we could do even better with creating a "hidden" or a "system" profile that would be just written to `/var/lib/kubelet/seccomp/operator/` and thus non-namespaced. `spod/spod` might list them in the status and the list could also be restricted with `spod.spec` to make sure someone doesn't sneak in their own. By default we'd write the `runc` and `crun` profiles. We'd probably have to somehow distinguish between a "real" profile and a "system" profile when using `baseProfileName`. Maybe we could just use a new attribute (`runtimeProfileBase`?).

The systemd profiles do this better IMO, with their inheritance from System profiles.

#### Why is this needed:
Currently every namespace where profiles that inherit from the runtime profiles must create the runtime profiles again.

#### User story covered
As an application SRE, Rajesh would like to deploy a Seccomp profile and an SELinux or AppArmor profiles to secure their application.

**Comment by saschagrunert** [comment]
Great idea! FWIW the current default profiles are there: 

https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/internal/pkg/manager/spod/bindata/default_profiles.go
