### ISSUE TITLE
Get a project logo

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#1325]
I think having a project logo would help the SPO to boost visibility within the community. The logo could also be re-used for operator hub and similar.

**Comment by jhrozek** [comment]
+1, my laptop lid only has one sad, lonely RHEL-9 sticker. It absolutely needs an SPO sticker!

**Comment by saschagrunert** [comment]
Do we have someone who could support us with that?

**Comment by pjbgf** [comment]
Yep, that's a great idea.

@saschagrunert CNCF seems to offer this type of service: https://www.cncf.io/services-for-projects/#design-and-aesthetics.
Do you have access to the [CNCF Service Desk](https://cncfservicedesk.atlassian.net/)?

I am not entirely sure how it works for projects under kubernetes-sigs, but for projects directly under CNCF you just need to open a ticket.

**Comment by pjbgf** [comment]
I tried to open a ticket but their site is within a scheduled maintance window right now.
I think we should ask for both logo and a website, so we have an external place where we can share high level info about the project. I will try again once the service desk is live again.

**Comment by pjbgf** [comment]
I have created a request for Logo and Website (CNCFSD-1502). Let me know if any of you have a Service Desk account so I can share the ticket with you. Hopefully we get a reply soon. :crossed_fingers:

**Comment by saschagrunert** [comment]
I had access to the CNCF service desk, but my account does not seem to exist any more. Anyways, thank you for opening the ticket @pjbgf. 

How will the website work? Do we get a domain, or will we host the website via GitHub pages directly?

**Comment by pjbgf** [comment]
I am not sure how the website works, I am waiting for them to come back on the ticket to get more information about it.

For the logo, I am assuming it is similar to the Security Audit services, in which we will have a follow-up meeting to discuss expectations. So as soon as I heard more I will relay here.

**Comment by pjbgf** [comment]
Still waiting for a reply, sent a bump today.

/remove-lifecycle stale

**Comment by pjbgf** [comment]
So far no updates, sending a chaser.

/remove-lifecycle stale

**Comment by pjbgf** [comment]
Got a reply from CNCF  Today:

> For Kubernetes related work, they work through Kubernetes Steering Committee.
> We’re still happy to help – maintainers.cncf.io has the list of KSC members that work with us for project-related work.

I will ping the KSC on this.

**Comment by saschagrunert** [comment]
@pjbgf do we still want this? :)

**Comment by pjbgf** [comment]
@saschagrunert I closed this one by mistake, I think we are still keen on a project logo.
