### ISSUE TITLE
Define groupName for new SeccompProfile CRD

### ISSUE THREAD

**Issue by cmurphy** [kubernetes-sigs/security-profiles-operator#135]
The `groupName` for the new SeccompProfile CRD is based on the current name of the operator which [may soon change](https://github.com/kubernetes-sigs/seccomp-operator/issues/127). It may also make sense to append `.k8s.io` or `.kubernetes.io` to the name since it is part of an official kubernetes SIG, but this [requires approval](https://github.com/kubernetes/enhancements/pull/1111). Once a decision is reached about the new name for the operator, we should revisit the `groupName` of the CRD.

**Comment by pjbgf** [comment]
On yesterday's sig-node we got a few +1 on the new name `security-operators-operator`, we should be OK to rename the `groupName` based on that.

**Comment by pjbgf** [comment]
This is tackled by https://github.com/kubernetes-sigs/security-profiles-operator/pull/139
