### ISSUE TITLE
AppArmorProfile: Add mode(enforce/complain) property in the CRD 

### ISSUE THREAD

**Issue by rahulroshan-kachchap** [kubernetes-sigs/security-profiles-operator#1399]
#### What would you like to be added:
Add a property value in the AppArmorProfile CRD to control modes(enforce/complain) of profiles.   

#### Why is this needed:
This enables users to have better control over what AppArmorProfile modes(enforce/complain) be whenever a new profile is created instead of profiles being in enforce mode by default.

#### User story covered
As an infrastructure SRE, Kirsti would like to create and apply an AppArmorProfile in complain mode or in enforce mode.

**Comment by pjbgf** [comment]
I like the idea. For this to work there are a few things that need to improve on how SPO manages the profile.
At the moment everything that is put into the profile content goes into the profile loaded by the kernel, so users can (with the current version) define the profile flags and make it be in enforce or complain modes.

What we can do instead is manage the "profile header" instead, and users can only define the profile contents. So things such as profile name, flags, includes could be defined based on fields on the CRD.

With that in mind, I think we could align a bit with the SELinux and make the current behaviour to live under a new `RawAppArmorProfile` kind. That gives users ultimate control, so they can rollout profiles across a cluster even when those profiles are to be used beyond Kubernetes clusters. Then have the `AppArmorProfile` kind be "managed" and targeted to Kubernetes workloads only, the entire profile header in this case would be managed by the SPO.
