### ISSUE TITLE
spod crashing with status CrashLoopBackOff

### ISSUE THREAD

**Issue by madantnk** [kubernetes-sigs/security-profiles-operator#1404]
#### What happened:

SPO is deployed in a cluster with 30 nodes
spod pods are crashing after starting for a few minutes with the error - CrashLoopBackOff
all desired 29 spods are crashing. We don't face this issue on other clusters. Is not clear what exactly is causing this.
all the spods should be running. please check the spod attached log

architecture: amd64
containerRuntimeVersion: docker://20.10.17
kernelVersion: 5.4.226-129.415.amzn2.x86_64
kubeProxyVersion: v1.21.14-eks-ba74326
kubeletVersion: v1.21.14-eks-ba74326
operatingSystem: linux
osImage: Amazon Linux 2

Log:
spod pods crashing => 

pod/spod-57l47 1/2 CrashLoopBackOff 237 19h
pod/spod-5gjxb 1/2 CrashLoopBackOff 232 19h

Log from spod pods =>
[spoderror1.txt](https://github.com/kubernetes-sigs/security-profiles-operator/files/10359104/spoderror1.txt)

#### What you expected to happen:

spod should be running

#### How to reproduce it (as minimally and precisely as possible):
Normal installation with default settings

#### Environment:

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): 

architecture: amd64
containerRuntimeVersion: docker://20.10.17
kernelVersion: 5.4.226-129.415.amzn2.x86_64
kubeProxyVersion: v1.21.14-eks-ba74326
kubeletVersion: v1.21.14-eks-ba74326
operatingSystem: linux
osImage: Amazon Linux 2

- Kernel (e.g. `uname -a`):
5.4.226-129.415.amzn2.x86_64
- Others:

**Comment by madantnk** [comment]
Hi, @ccojocar @saschagrunert could you please look into this and help.

**Comment by ccojocar** [comment]
@madantnk Do you have the profile recorder enabled in the daemon configuration? Did you try on a similar size cluster (similar number of nodes and running pods)? Are the other cluster smaller where it works?

This looks similar with https://github.com/kubernetes-sigs/security-profiles-operator/issues/1386.

**Comment by madantnk** [comment]
Hi @ccojocar Thank you for looking this.
We are not using profile recorder and we have similar size clusters on which SPO is running well.
We had issue reported on a couple of clusters. We tried increasing the RAM and CPU but no luck. Let me know if you need any further info on this. TIA

**Comment by kecebon9** [comment]
Hi @ccojocar 
I noticed that if i've changed the [security-profiles-operator.json](https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/operator.yaml#L2797) `defaultAction` to `SCMP_ACT_LOG` the spod are running fine and stable. So far we only found this issue on 2 cluster, the rest are working fine.
So i believe there is syscall got blocked (Please correct me if i'm wrong). Unfortunately when i set it to `SCMP_ACT_LOG`, i can't see any syscall logged on the worker node (we have limitted access to the node).

what i did to test this:
- Edit `security-profiles-operator` configmap by updating `defaultAction: SCMP_ACT_ERRNO` to `defaultAction: SMCP_ACT_LOG`
  - `kubectl edit configmap -n security-profiles-operator security-profiles-operator-profile`
- flip the verbosity setting on or off to restart spod
  - `kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"verbosity":1}}'`  

Could you please advise?. Thanks

**Comment by ccojocar** [comment]
> So i believe there is syscall get blocked (Please correct me if i'm wrong). Unfortunately when i set it to SCMP_ACT_LOG, i can't see any syscall logged on the worker node (we have limited access to the node).

You should normally see the logged actions in the audit log file if is the audit daemon is enabled in your Linux distribution. Otherwise you can also see them in the kernel syslog. Can you check if audit logging is enabled?

As I understand form issue description, you are running the operator on EKS, are the worker nodes running the default AWS Linux distribution? I believe the operator wasn't tested with this Linux distribution. There are E2E tests for Fedora, Ubuntu and Flatcar Linux.

**Comment by kecebon9** [comment]
> You should normally see the logged actions in the audit log file if is the audit daemon is enabled in your Linux distribution. Otherwise you can also see them in the kernel syslog. Can you check if audit logging is enabled?
I'll see and check again if i can get this.

> As I understand form issue description, you are running the operator on EKS, are the worker nodes running the default AWS Linux distribution? I believe the operator wasn't tested with this Linux distribution. There are E2E tests for Fedora, Ubuntu and Flatcar Linux.
We're running the default Amazon Linux 2
```
architecture: amd64
kernelVersion: 5.4.226-129.415.amzn2.x86_64
operatingSystem: linux
osImage: Amazon Linux 2
```

**Comment by kecebon9** [comment]
I found the log, and below are the syscalls that not in the `security-profiles-operator.json`, i'll try to add to existing seccomp profile and update if this fix the issue.

audit.log
```
type=SECCOMP msg=audit(1673445430.716:52211): auid=1234 uid=65535 gid=65535 ses=1234 pid=12390 comm="security-profil" exe="/usr/bin/security-profiles-operator" sig=0 arch=1234 syscall=273 compat=0
type=SECCOMP msg=audit(1673445430.716:52209): auid=1234 uid=65535 gid=65535 ses=1234 pid=12390 comm="security-profil" exe="/usr/bin/security-profiles-operator" sig=0 arch=1234 syscall=11 compat=0 
type=SECCOMP msg=audit(1673445426.508:52169): auid=1234 uid=65535 gid=65535 ses=1234 pid=12390 comm="security-profil" exe="/usr/bin/security-profiles-operator" sig=0 arch=1234 syscall=201 compat=0 
type=SECCOMP msg=audit(1673445426.484:52151): auid=1234 uid=65535 gid=65535 ses=1234 pid=12390 comm="security-profil" exe="/usr/bin/security-profiles-operator" sig=0 arch=1234 syscall=97 compat=0
```

the syscalls:
```
11     munmap
201    time
273    set_robust_list
97     getrlimit
```

**Comment by kecebon9** [comment]
This issue is fixed by adding the following syscalls into `security-profiles-operator.json` configmap. This issue can be closed. Thank you.
```
11     munmap
201    time
273    set_robust_list
97     getrlimit
```
cc: @madantnk
