### ISSUE TITLE
Dynamic Seccomp Profiles based on Cluster-level rules to Enforce syscalls

### ISSUE THREAD

**Issue by pjbgf** [kubernetes-sigs/security-profiles-operator#142]
#### What would you like to be added:

Custom seccomp profiles could be dynamically modified to always allow specific system calls.
The always allowed system calls would be low risk/impact and built into the operator.

#### Why is this needed:

Some essential system calls (e.g. `exit`, `exit_group`) can be left out of seccomp profiles leading to containers being caught up on endless exit loops, as reported [here](https://github.com/kubernetes/kubernetes/issues/85191). This is a non-deterministic behaviour, meaning that the same profile and container combination may have the issue in one kernel/platform, and not have it in another.

**Comment by saschagrunert** [comment]
Sounds good! How would an API look like?
