### ISSUE TITLE
Any specific reason for Kube-rbac-proxy:v0.13.1 being referenced from an individual repo

### ISSUE THREAD

**Issue by harshadsonde** [kubernetes-sigs/security-profiles-operator#1423]
What happened:
One of the environment package being used "kube-rbac-proxy" image is being taken from repo  "quay.io/brancz/kube-rbac-proxy:v0.13.1"
Is there a specific reason that the image is being referenced from the above mentioned individual repo ? As we can see that similar image is also available at "gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1" ?

What you expected to happen:
Can the image of kube-rbac-proxy be referenced from "gcr.io/kubebuilder/kube-rbac-proxy" instead of
"quay.io/brancz/kube-rbac-proxy:v0.13.1" repo ?

How to reproduce it (as minimally and precisely as possible):
The above repo link is referenced under deployment.yaml file.

**Comment by saschagrunert** [comment]
Hm we started to use kube-rbac-proxy with version v0.9.0 and maybe they switcher later on to the `kubebuilder` org. We should definitely fix that. Do you mind opening a PR for that @harshadsonde?
