### ISSUE TITLE
The image with the latest tag in your container registry which was updated 5 hours ago is broken

### ISSUE THREAD

**Issue by elucidsoft** [kubernetes-sigs/security-profiles-operator#1480]
#### Anything else we need to know?:  I believe this is 100% related to the update 5 hours ago in the Container Registry located here: https://console.cloud.google.com/gcr/images/k8s-staging-sp-operator/GLOBAL/security-profiles-operator

The latest tag was bumped, I think the latest tag needs to be reverted back to a known stable version.

#### Environment:

- Cloud provider or hardware configuration: GKE 1.23.14-gke.1800
- OS (e.g: `cat /etc/os-release`): GKE
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by elucidsoft** [comment]
I switched my deployment to use: https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/v0.6.0/deploy/operator.yaml and now everything is working. But again, the script on Google Docs website does not use the version numbered one it uses main, so anyone who was using main is now broken because of the latest tag being moved to the dev version.

**Comment by saschagrunert** [comment]
Hey @elucidsoft, do you think you can share some logs of the failure itself?

**Comment by elucidsoft** [comment]
Hi, it actually wasn't producing any logs at all. When I looked the entire log output was {} and that was it.
