### ISSUE TITLE
Automatic selinuxd image selection

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#1576]
#### What would you like to be added:
SPO to be able to automatically select the appropriate selinuxd image for the nodes where the SPOD DS is running on.

#### Why is this needed:
Different OSs have different libsemanage versions and the version of libsemanage inside the selinuxd container must match the version of libsemanage on the host.

#### User story covered
As an infrastructure SRE, Kirsti wants to make sure that no security profiles are in an errored state

#### High level design
First, selinuxd images  must exist for the target OS. The list of possible (approved) selinuxd images must be available to SPO.

Next, because the image must be known before the DS is created, the selection must be performed by the operator, probably by the spod controller. A new workload that examines the target nodes should probably be created. 

#### More detailed design proposal

1. the list of approved images would be created as a deploy time manifest, similarly to how we create the seccomp profile for the SPO. The format will be a configMap where the key is the `CPE_NAME` key in the `/etc/os-release` file and the value is a pullspec of selinuxd.
2. The spod controller will be adjusted so that if selinuxd is enabled, a `Job` will be created with the configMap mentioned above. This job will be privileged, but the only thing it will do is to read `/etc/os-release` and write the appropriate selinuxd pullspec into the spod status.
3. this pullspec will be then used by the DS

#### Questions

- What should the semantic of `RELATED_IMAGE_SELINUXD` be? IMO if that variable is set, then the selection above should not be performed and the related image should be used.
- What if the selection fails? Is there another option than failure? (I don't think so)

**Comment by jhrozek** [comment]
> @jhrozek so, to be clear. Before starting the SPOd, a new workload would be created by the manager to get information on the OS from a host that matches the selector?

Actually after some more poking this should not be needed. We could use [NodeSystemInfo](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#nodesysteminfo-v1-core) and check the `osImage` field. No need to mount `/etc/os-release`.

But otherwise yes, the idea is to run a NodeList with the same selector as the spod, and try to match the `osImage` against a pre-approved list of selinuxd images.

**Comment by JAORMX** [comment]
@jhrozek sounds like a plan!
