### ISSUE TITLE
SPO Daemonset values are not configurable

### ISSUE THREAD

**Issue by tuxerrante** [kubernetes-sigs/security-profiles-operator#1592]
#### What happened:
The daemonset CRD is correctly generated in the makefile during a kustomize build targeting the helm folder
`$(BUILD_DIR)/kustomize build deploy/base-crds -o deploy/helm/crds/crds.yaml`
https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/Makefile#L182

Then at runtime this daemonset should be generated based on the[ chart values.yaml](https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/helm/values.yaml) to install profiles on the mounted node.

The issue is here, since the daemonset seems to be generated always from static values, ignoring namespace changes, dnsNames changes (#1591 ) taints, tolerations etc...

We have nodes tolerations and taints so we need to schedule only on specific nodes, this is blocking daemonset pods to spawn, which is critical for the basic operation.

#### What you expected to happen:
SPOD whould have same values as the deployment manager, taking them from the chart values.

#### How to reproduce it (as minimally and precisely as possible):
Install the chart on a cluster with taints.
Pods won't be able to start if not manually patching the daemonset with a toleration.
After any pod deletion or daemonset restart the pods won't be scheduled again sine they will be reset.

#### Environment:
Any Kubernetes supporting taints

@stephen-fox maybe?

**Comment by tuxerrante** [comment]
Still relevant.

**Comment by saschagrunert** [comment]
@hans-fischer thank you for the ping on this issue. Do you consider to contribute the required changes to fix that problem?

**Comment by hans-fischer** [comment]
I'm afraid I don't have the right skills to work on go-lang code. I have written one small projekt but never understood some basic go-lang prinziples.
