### ISSUE TITLE
SELinux profile support

### ISSUE THREAD

**Issue by JAORMX** [kubernetes-sigs/security-profiles-operator#163]
Some time ago, we noticed a gap in how folks install SELinux modules for their workloads, and came up with an operator to do just that: https://github.com/JAORMX/selinux-operator . The intent of that project is to be able to create SELinux policies as Custom Resources, and to be able to install them and take them into use on a per-namespace basis. So it comes with the controller that reads policies and schedules workloads to install them, as well as a webhook to validate that folks aren't able to use policies that are not installed in the namespaces. So, to some extent, it has a very similar model to the security-profile-operator.

If you'd like a bit more of an explanation and to see it in action, we gave a talk about it in DevConf this year: https://www.youtube.com/watch?v=iMO6rwA-i_s

### Let's merge the projects!

This would come in the form of adding the SELinux policy types, controllers, and webhook from the selinux-operator to be part of the selinux-profiles-operator instead.

## Why is this needed:

It would add SELinux support.

**Comment by JAORMX** [comment]
Let me know what you think. If folks dig the idea I could start bringing the code over and get feedback on the PR itself

**Comment by saschagrunert** [comment]
> Let me know what you think. If folks dig the idea I could start bringing the code over and get feedback on the PR itself

I think that's a gorgeous idea. It would be wonderful if you'd like to contribute the code directly. :heart: 

The overall approach seems quite similar, right? So feel free to kick that off the stage :raised_hands:

**Comment by JAORMX** [comment]
Great! What tool are y'all using to generate controllers and such? Kubebuilder directly, operator-sdk or something else?

**Comment by saschagrunert** [comment]
> Great! What tool are y'all using to generate controllers and such? Kubebuilder directly, operator-sdk or something else?

Yes, I think we used kubebuilder directly. @cmurphy can share the details :+1: 

https://github.com/kubernetes-sigs/security-profiles-operator/blob/43abbff6270cc30fd9ff3d8be7a78f4c65713da4/api/v1alpha1/seccompprofile_types.go#L38

**Comment by cmurphy** [comment]
Yes we used kubebuilder to help scaffold out the types and parts of the controller, though TBH the controller already existed when I started working on it and I'm not positive how it was generated initially.

**Comment by pjbgf** [comment]
> I could start bringing the code over and get feedback on the PR itself

@JAORMX  that would be awesome! :rocket: 


> Yes we used kubebuilder to help scaffold out the types and parts of the controller, though TBH the controller already existed when I started working on it and I'm not positive how it was generated initially.

I think that @hasheddan manually created the controller without any tooling.
