### ISSUE TITLE
 "error"="updating SeccompProfile: updating SeccompProfile

### ISSUE THREAD

**Issue by jouros** [kubernetes-sigs/security-profiles-operator#168]
#### What happened:
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1  
kind: SeccompProfile  
metadata:  
  name: whitelist  
  namespace: default  
spec:  
  defaultAction: SCMP_ACT_ERRNO  
  targetWorkload: custom-profiles  
  architectures:  
  - SCMP_ARCH_X86_64  
  syscalls:  
  - action: SCMP_ACT_LOG  
    names:  
    - _llseek  
    - _newselect  
    - accept  
long list here  

kubectl create -f whitelist.yaml  

kubectl get seccompprofile -o wide   
NAME        STATUS   AGE   LOCALHOSTPROFILE  
whitelist   Active   19m   operator/default/custom-profiles/whitelist.json  

kubectl logs security-profiles-operator-2n7wx -n security-profiles-operator  
E1213 16:36:52.535201       1 controller.go:246] controller "msg"="Reconciler error" "error"="updating SeccompProfile: updating SeccompProfile: Operation cannot be fulfilled on seccompprofiles.security-profiles-operator.x-k8s.io \"whitelist\": the object has been modified; please apply your changes to the latest version and try again" "controller"="pods" "name"="busyboxsecc" "namespace"="default" "reconcilerGroup"="" "reconcilerKind"="Pod"  

Files is in correct place: ls  /var/lib/kubelet/seccomp/operator/default/custom-profiles/whitelist.json  
/var/lib/kubelet/seccomp/operator/default/custom-profiles/whitelist.json  

kubectl get pods  
NAME          READY   STATUS   RESTARTS   AGE  
busyboxsecc   0/1     Error    0          27s  

#### What you expected to happen:
Profile being loaded and Pod being running

#### How to reproduce it (as minimally and precisely as possible):
Happened also after re-install of security-profiles-operator. 

#### Environment:

- Cloud provider or hardware configuration: selfmade KVM K8s
- OS (e.g: `cat /etc/os-release`): Debian 10
- Kernel (e.g. `uname -a`): Linux master1 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
- Others: cri-o runtime, kube version 1.20.0

**Comment by cmurphy** [comment]
Can you check if the file is in the correct place for every node, especially the node where the pod is scheduled? That would indicate that the error message in the logs is unrelated since the profile was actually applied. I created a PR to help with those misleading logs: https://github.com/kubernetes-sigs/security-profiles-operator/pull/171

If the profile is deployed everywhere, then there is something wrong with the pod. Can you show your pod's YAML manifest, and the events in `kubectl describe pod <pod>`, and any logs from the pod itself? The pod might be referencing the wrong profile, or maybe one of the syscalls it is making is not in the whitelist, or maybe something else.

**Comment by jouros** [comment]
1) I did fresh operator install  
2) I deployed below seccomp profile
cat audit.yaml   
`---  
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1  
kind: SeccompProfile  
metadata:  
  name: audit   
  namespace: default
spec:
  defaultAction: SCMP_ACT_LOG
  targetWorkload: custom-profiles 
  architectures:
  - SCMP_ARCH_X86_64`

kubectl apply -f audit.yaml     
seccompprofile.security-profiles-operator.x-k8s.io/audit created  

kubectl get seccompprofile -o wide  
NAME    STATUS   AGE    LOCALHOSTPROFILE  
audit   Active   4m8s   operator/default/custom-profiles/audit.json    

audit.json was in every node: /var/lib/kubelet/seccomp/operator/default/custom-profiles/audit.json  

cat busybox-seccomp.yaml  
`---
apiVersion: v1
kind: Pod
metadata:
  name: busyboxsecc 
  creationTimestamp: null
  labels:
    app: busyboxsecc
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/default/custom-profiles/audit.json 
  containers:
   - name: busybox 
     image: busybox 
     command: 
       - sleep
       - "86400"
     imagePullPolicy: IfNotPresent
  restartPolicy: Never`

There was some errors still in operator logs:  
kubectl logs security-profiles-operator-bv8ss -n security-profiles-operator  
E1215 12:03:47.526818       1 profile.go:386] profile "msg"="could not update seccomp profile for pod" "error"="updating SeccompProfile status: exceeded 5 retries: Operation cannot be fulfilled on seccompprofiles.security-profiles-operator.x-k8s.io \"audit\": the object has been modified; please apply your changes to the latest version and try again" "namespace"="default" "pod"="busyboxsecc" 

E1215 12:03:47.527057       1 controller.go:246] controller "msg"="Reconciler error" "error"="updating SeccompProfile pod references for new or updated pod: updating SeccompProfile status: exceeded 5 retries: Operation cannot be fulfilled on seccompprofiles.security-profiles-operator.x-k8s.io \"audit\": the object has been modified; please apply your changes to the latest version and try again" "controller"="pods" "name"="busyboxsecc" "namespace"="default" "reconcilerGroup"="" "reconcilerKind"="Pod"

kubectl describe pod busyboxsecc    
Annotations:  seccomp.security.alpha.kubernetes.io/pod: localhost/operator/default/custom-profiles/audit.json  

Now the last line in operator logs is:  
I1215 12:17:36.503457       1 profile.go:323] profile "msg"="Reconciled profile from SeccompProfile" "namespace"="default" "profile"="audit" "name"="audit" "resource version"="59356"

Now I'm not sure what is status here, is my audit.json used or not or is it still using runtime/default? From the node logs I can see some syscalls but not all of them as I expected?

**Comment by jouros** [comment]
It seems that profile operator is doing its job as expected and my problems are related to something else, so this issue can be closed.
