### ISSUE TITLE
feat: write unique policy for each record 

### ISSUE THREAD

**Issue by kranurag7** [kubernetes-sigs/security-profiles-operator#1721]
#### What would you like to be added:
If there are two binary on a system and I invoke two commands. 
```bash
$ spoc record ./binary_one
$ spoc record ./binary_two
```
The first file that's written on the disk at `/tmp/profile.yaml` is overwritten by the second one. 

#### Why is this needed:
I think it will be great to have something like `kubectl` where each file written while invoking `kubectl edit` and something goes wrong is unique. e.g. `profile_12009.yaml` for the first binary and `profile_89233.yaml` for the second one.

**Comment by saschagrunert** [comment]
Hey @kranurag7, thank you for the input here! I've chosen `/tmp/profile.yaml` because it's easy to pickup a default for further subcommands like `spoc run`. May we could add an overwrite prompt at the end of `spoc record`. :thinking:
