### ISSUE TITLE
How to log only unique syscalls in audit log file - Security-Profiles-Operator

### ISSUE THREAD

**Issue by madantnk** [kubernetes-sigs/security-profiles-operator#1899]
Hi Team
When enabled SPO in our clusters, we see lots of logs are being logged in log file.
we have large number of clusters, and the log are growing to TB's of data per day.
We have disabled the log currently.
Is there any option to log only the Unique syscall to reduce the log size?
Please advise/help
Thanks!

**Comment by madantnk** [comment]
@kecebon9

**Comment by saschagrunert** [comment]
Hey @madantnk, thank you for the report! Hm, so I assume the log enricher is the cause for that and it's enabled in the cluster? Or which kind of logs are you referring to?

**Comment by madantnk** [comment]
Hi @saschagrunert  Thanks for the response.
It is about the audit log.
How to disable the log enricher?
disabling the log enricher will disable the audit log?
If I disable it will I get the syscall information?
Please advise

**Comment by saschagrunert** [comment]
@madantnk yes you can disable the log enricher: https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/installation-usage.md#using-the-log-enricher

By:

```
kubectl patch -n security-profiles-operator spod spod -p '{"spec":{"enableLogEnricher": false}}' --type=merge
```
