### ISSUE TITLE
Support for --http2-disable flag in metrics pod

### ISSUE THREAD

**Issue by barapz** [kubernetes-sigs/security-profiles-operator#1974]
#### What happened:
Azure AKS automatically sets the args:
- --http2-disable

for the daemonset.

Unfortunately the SPO is still using gcr.io/kubebuilder/kube-rbac-proxy:v0.14.0 where this flag is not yet supported.
Can we upgrade to [gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0](https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.15.0) where the support for this flag has been implemented?

#### What you expected to happen:
A working helm chart

#### How to reproduce it (as minimally and precisely as possible):
Install Helm Chart in AKS.

#### Environment:

- Cloud provider or hardware configuration: Azure AKS 1.27
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
@barapz we did that upgrade in https://github.com/kubernetes-sigs/security-profiles-operator/pull/1940 and need a new release for it. We can plan for a new one before the end of the year if that fits for your needs.

**Comment by barapz** [comment]
@saschagrunert I didn't see that commit, thanks for pointing it out!
That'd be great. I think it could affect more AKS customers in the future.
