### ISSUE TITLE
AKS spod STATE : UPDATING

### ISSUE THREAD

**Issue by sybadm** [kubernetes-sigs/security-profiles-operator#1981]
I'm trying to install SPO on AKS 1.27.3

#### What happened:
spod stuck in STATE: UPDATING and changing to RUNNING

$ kubectl -nsecurity-profiles-operator get spod spod
NAME   STATE
spod   UPDATING

#### What you expected to happen:
$ kubectl -nsecurity-profiles-operator get spod spod
NAME   STATE
spod   RUNNING

#### How to reproduce it (as minimally and precisely as possible):
1. Install cert-manager
`$ kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml`
`$ kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager`

2. Install OLM
    `curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.26.0/install.sh -o install.sh
`     
     `chmod +x install.sh`
      `./install.sh v0.26.0`

3. Install SPO
    `kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/deploy/operator.yaml`
     `kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/examples/olm/operatorhub-io.yaml`

4. AKS Webhook conf

`
kubectl -nsecurity-profiles-operator patch spod spod  --type=merge \
    -p='{"spec":{"webhookOptions":[{"name":"binding.spo.io","namespaceSelector":{"matchExpressions":[{"key":"control-plane","operator":"DoesNotExist"}]}},{"name":"recording.spo.io","namespaceSelector":{"matchExpressions":[{"key":"control-plane","operator":"DoesNotExist"}]}}]}}'
`

#### Environment:

- Cloud provider or hardware configuration:
- Azure AKS 1.27.3

- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
Hey @sybadm, thank you for the request. Can you share the logs of the components of the SPO?

**Comment by sybadm** [comment]
@saschagrunert thanks for your response


`$ kubectl -nsecurity-profiles-operator describe spod spod
Name:         spod
Namespace:    security-profiles-operator
Labels:       app=security-profiles-operator
Annotations:  <none>
API Version:  security-profiles-operator.x-k8s.io/v1alpha1
Kind:         SecurityProfilesOperatorDaemon
Metadata:
  Creation Timestamp:  2023-11-27T09:36:43Z
  Generation:          1
  Managed Fields:
    API Version:  security-profiles-operator.x-k8s.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app:
      f:spec:
        .:
        f:disableOciArtifactSignatureVerification:
        f:hostProcVolumePath:
        f:priorityClassName:
        f:selinuxOptions:
          .:
          f:allowedSystemProfiles:
        f:selinuxTypeTag:
        f:staticWebhookConfig:
        f:tolerations:
        f:webhookOptions:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-11-27T09:36:43Z
    API Version:  security-profiles-operator.x-k8s.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:state:
    Manager:         security-profiles-operator
    Operation:       Update
    Subresource:     status
    Time:            2023-11-27T09:36:43Z
  Resource Version:  34354236
  UID:               6bbe9b21-9a61-489d-9fa9-90767c7b2918
Spec:
  Disable Oci Artifact Signature Verification:  false
  Host Proc Volume Path:                        /proc
  Priority Class Name:                          system-node-critical
  Selinux Options:
    Allowed System Profiles:
      container
  Selinux Type Tag:       spc_t
  Static Webhook Config:  false
  Tolerations:
    Effect:    NoSchedule
    Key:       node-role.kubernetes.io/master
    Operator:  Exists
    Effect:    NoSchedule
    Key:       node-role.kubernetes.io/control-plane
    Operator:  Exists
    Effect:    NoExecute
    Key:       node.kubernetes.io/not-ready
    Operator:  Exists
  Webhook Options:
    Name:  binding.spo.io
    Namespace Selector:
      Match Expressions:
        Key:       control-plane
        Operator:  DoesNotExist
    Name:          recording.spo.io
    Namespace Selector:
      Match Expressions:
        Key:       control-plane
        Operator:  DoesNotExist
Status:
  Conditions:
    Last Transition Time:  2023-11-27T09:36:43Z
    Message:
    Reason:                Updating
    Status:                False
    Type:                  Ready
  State:                   UPDATING
Events:
  Type     Reason            Age   From         Message
  ----     ------            ----  ----         -------
  Warning  CannotUpdateSPOD  18s   spod-config  updating operator DaemonSet: Operation cannot be fulfilled on daemonsets.apps "spod": the object has been modified; please apply your changes to the latest version and try again
`

**Comment by saschagrunert** [comment]
@sybadm it should work, can you update the configuration and see if it gets into the right state?

**Comment by sybadm** [comment]
> @sybadm it should work, can you update the configuration and see if it gets into the right state?

Which configuration I need to update

**Comment by saschagrunert** [comment]
@sybadm the spod, for example by setting the log level:

```
kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"verbosity":1}}'
```

**Comment by saschagrunert** [comment]
@sybadm you don't have to install the OLM at all, but I think I can reproduce the issue on AKS.

**Comment by sybadm** [comment]
> @sybadm you don't have to install the OLM at all, but I think I can reproduce the issue on AKS.

Thanks you so much @saschagrunert  for taking a look at it.  Really appreciate your time.

As you suggested I tried , but no luck

`kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"verbosity":1}}'`

**Comment by saschagrunert** [comment]
I have a fix in https://github.com/kubernetes-sigs/security-profiles-operator/pull/1985

**Comment by sybadm** [comment]
> I have a fix in #1985

Excellent

**Comment by saschagrunert** [comment]
@sybadm may I ask you to verify the fix once https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-security-profiles-operator-push-image/1729505403827392512 is successfull and we have an updated `latest` image tag?

**Comment by sybadm** [comment]
> @sybadm may I ask you to verify the fix once https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-security-profiles-operator-push-image/1729505403827392512 is successfull and we have an updated `latest` image tag?

you made my day!

```
$ kubectl -nsecurity-profiles-operator get spod spod
NAME   STATE
spod   RUNNING
```
