### ISSUE TITLE
Create distinct cluster-bound and namespace-bound resources

### ISSUE THREAD

**Issue by JAORMX** [kubernetes-sigs/security-profiles-operator#199]
## Context

Currently, the resources (SeccompProfile and SelinuxPolicy) are bound according to the deployment of the operator. For this, we have two distinct [kustomize overlays](https://github.com/kubernetes-sigs/security-profiles-operator/tree/master/deploy/overlays) called `cluster` and `namespaced`, which set the RBAC and Deployment mode, amongst other things.

## What would you like to be added:

The proposal is to have two types per resource:

* A "cluster" scoped resource which would be accessible from all namespaces
* A "namespaced" resource which would only be accessible from the namespace it was created.

e.g.

We would have:

* `ClusterSeccompProfile` and `ClusterSelnuxPolicy` as cluster-scoped resources
* `SeccompProfile` and `SelinuxPolicy` as namespace-scoped resources

This is similar to how other kube resources are scoped. e.g. `ClusterRole` and `Role`.

### Less maintenance

This would allow us to have a more unified deployment model (no need for two overlays) where we could start auto-generating our  RBAC rules with kubebuilder (less maintenance burden).

### Unifies use-cases

This would also enable the use-cases of both overlays in one operator, as opposed to having to deploy the two overlays.

### Shared policies

Finally, it would also allow deployers to create cluster-wide policies for common scenarios. e.g. A cluster-wide SeccompProfile that's usable for nginx-based web-services. Validation of permissions can be done via a webhook.

**Comment by saschagrunert** [comment]
I really like this idea and I'm in favor of adding it. I think we may have to refactor some code parts to be re-usable across both (cluster and namespaced) types. :+1:

**Comment by saschagrunert** [comment]
Who wants to work on the seccomp bits? @cmurphy @pjbgf I can also take it but would like to give you precedence :innocent:

**Comment by JAORMX** [comment]
@saschagrunert I can work on this.

**Comment by saschagrunert** [comment]
@JAORMX do we wanna bring this into v0.3.0, too?
/remove-lifecycle stale

**Comment by JAORMX** [comment]
@saschagrunert I don't think this is needed for v0.3.0

**Comment by JAORMX** [comment]
I think we can close this, we have no concrete use-cases really.
