### ISSUE TITLE
getting owner profile: the node status owner is of an unknown kind

### ISSUE THREAD

**Issue by NahumLitvin** [kubernetes-sigs/security-profiles-operator#1993]
we are using app armor, and this functions fails with error as it doesn't handle AppArmorProfile kind...

https://github.com/kubernetes-sigs/security-profiles-operator/blob/cacffc8d09614757d72bdbea9e9301775ef5375f/internal/pkg/manager/nodestatus/nodestatus.go#L250

is this important? does it mean something is wrong?
it seems that only effect is millions of log messages...
can I get guidence how to fix this via PR?

**Comment by saschagrunert** [comment]
@NahumLitvin thank you for the report! Yeah I assume that we have to add apparmor to the node status as well. Do you plan to contribute that?

**Comment by NahumLitvin** [comment]
resolved in https://github.com/kubernetes-sigs/security-profiles-operator/pull/1994
