### ISSUE TITLE
Manage SELinux booleans

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#1997]
> SELinux Booleans are switches that contains a set of rules to make a selective adjustment in behavior to an SELinux policy. SELinux Booleans provide an easy interface to change the behavior of an SELinux policy rule.

It would be interesting if the operator could toggle SELinux booleans combined with policies. I'm not exactly sure if we would require a new CRD for this, but the API would require an extension in any case.

**Comment by JAORMX** [comment]
I don't think we'd explicitly need a CRD for this. I think it would be appropriate to add such a configuration to the SPOD CRD instead.

**Comment by JAORMX** [comment]
I don't have a list ready from the top of my head. The tricky thing is that a given system might have many. It would surely be easier just to take a plain map and issue an event if it's not supported. But that doesn't provide for great usability, as an administrator wouldn't have a good notion of what's available. On the other hand, adding the available booleans as a status would also be quite overwhelming. I don't have a good answer for this... The best thing I can think of is having the SPOD output the booleans to a configmap, and store the config map reference in the SPOD's status.

If we merely want to have support for folks easily toggling booleans, the plain map is the best I can think of.

**Comment by saschagrunert** [comment]
@JAORMX sounds good to me! I'm not sure if the list of available booleans would vary across systems, then we could not plainly sync them from a config map or status field.

Having a plain map which the SPO tries to enforce seems the best way forward, though.

**Comment by JAORMX** [comment]
@saschagrunert the booleans will vary accross systems depending on what policy they're based on. Basically, there are two main SELinux base policy groups out there:

* Upstream SELinux-based
* Fedora-based

They have variations in how policies are implemented and some booleans may also vary.

The ConfigMap outputting the booleans could be merely a status implementation... if nothing else.
