### ISSUE TITLE
Main operator Deployment is missing its seccomp profile

### ISSUE THREAD

**Issue by cmurphy** [kubernetes-sigs/security-profiles-operator#201]
#### What happened:

With the operator splitting part of its functionality from a `DaemonSet` to a `Deployment`, it lost its seccomp profile and the init code that set it up, which now only exists for the `DaemonSet`:

https://github.com/kubernetes-sigs/security-profiles-operator/commit/b44de6f0c5cae26a4c706da1aec0ac6b06f31669#diff-ee1324908347cf8841925458a9937fb58cd6593d4002af28b74a0071bb12dbf4L16

#### What you expected to happen:

The `Deployment` should still be run with a seccomp profile, at least if the administrator is choosing to run it with seccomp.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
Alright, at least adding the runtime/default seccomp profile should not hurt in the first place. 

To be able to use the same seccomp profile for the deployment, we would have to init the deployment in the same way we do it for the daemonset…
