### ISSUE TITLE
[Question] Disable webhook deployment

### ISSUE THREAD

**Issue by kecebon9** [kubernetes-sigs/security-profiles-operator#2056]
>I'm sorry if i put the query on this section

What the impact if we disable webhook deployment?, if we only use seccomp feature (for now) for the profile distribution only without profilebinding, etc.? is it safe?,
I tried locally, i still could create/delete the seccompprofile.

Thanks

**Comment by ccojocar** [comment]
It should work if you plan to only install the profile but don't do any recording. Also there is an option to disable the dynamic webhook created by the operator and deploy a static webhook via the deployment. You can have a look at https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/deploy/webhook-operator.yaml. Thanks

**Comment by kecebon9** [comment]
Thank you @ccojocar!
