### ISSUE TITLE
Seeing Policy Violations

### ISSUE THREAD

**Issue by meghna-pancholi** [kubernetes-sigs/security-profiles-operator#2060]
#### What would you like to be added: 

When a SeccompProfile's policy is violated, it would be helpful to easily see what violation occurred in the logs somewhere. For example if the "exec" system call caused a policy violation, then a log entry can report this violation. I apologize if this feature already exists. I was not able to figure out how to find this information easily and in a consistent format. 

From what I see, the logenricher only includes lines of the audit log where a syscall is reported, but not any where the violations are reported.  

#### Why is this needed: 

It would be helpful to quickly collect policy violation information from a program at runtime while enforcing a policy.

#### User story covered 

I am not sure if this is covered in a user story.

**Comment by saschagrunert** [comment]
Thank you for the feature request @meghna-pancholi! :pray: 

> if the "exec" system call caused a policy violation, then a log entry can report this violation

Can you share an example of that so that I can understand the feature better?

**Comment by meghna-pancholi** [comment]
Yes! This is an example of an audit log entry of a Seccomp violation: 

type=ANOM_ABEND msg=audit(1706114183.948:8264563): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=docker-default pid=2040848 comm="mkdir" exe="/bin/busybox" sig=31 res=1

Here, the offending system call is "mkdir". This is an audit log entry I saw by checking the audit log when I had a Seccomp filter with ACT_TRAP, but it was not reported by the log enricher.

**Comment by saschagrunert** [comment]
Ah so we basically need to support the `ANOM_ABEND` type? We can extend the enricher to allow that. But `ANOM_ABEND` can be caused by any signal, right? Not only seccomp violations.

**Comment by saschagrunert** [comment]
cc @pjbgf :point_up:
