### ISSUE TITLE
Move the e2e to ginkgo

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes-sigs/security-profiles-operator#211]
#### What would you like to be added:
Move the `e2e` tests to [ginkgo](https://onsi.github.io/ginkgo/)

#### Why is this needed:
I am proposing to utilize ginkgo for e2e testing instead of the standard go test. ginkgo is utilized by kubebuilder https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v2/plugin_cluster_test.go and comes as a standard package for any new CRD.

Ginkgo is BDD driven. It has features like `BeforeEach` and `AfterEach`
 Here is an example from Kubebuilder which shows makes the code clean and simple

```
BeforeEach(func() {
			var err error
			kbc, err = utils.NewTestContext(utils.KubebuilderBinName, "GO111MODULE=on")
			Expect(err).NotTo(HaveOccurred())
			Expect(kbc.Prepare()).To(Succeed())

			// Install cert-manager with v1beta2 CRs.
			By("installing cert manager bundle")
			Expect(kbc.InstallCertManager(true)).To(Succeed())

			By("installing prometheus operator")
			Expect(kbc.InstallPrometheusOperManager()).To(Succeed())
		})

		AfterEach(func() {
			By("clean up created API objects during test process")
			kbc.CleanupManifests(filepath.Join("config", "default"))

			By("uninstalling prometheus manager bundle")
			kbc.UninstallPrometheusOperManager()

			// Uninstall cert-manager with v1beta2 CRs.
			By("uninstalling cert manager bundle")
			kbc.UninstallCertManager(true)

			By("remove container image and work dir")
			kbc.Destroy()
		})
```

 
ginkgo can do parallel testing which will decrease the test completion time. It comes with builtin Wait features like `Eventually` 

`Eventually(verifyCurlUp, 30*time.Second, time.Second).Should(Succeed())
`

It has a rich API for writing tests.

IMO it is the ginkgo test is easier to read and maintain.

**Comment by saschagrunert** [comment]
Hey @naveensrinivasan, we already had the discussion about ginkgo in the past and explicitly decided against it. I guess we have now more maintainers onboard, which may share different thoughts.

**Comment by jhrozek** [comment]
On Tue, Jan 19, 2021 at 11:56:11PM -0800, Sascha Grunert wrote:
> Hey @naveensrinivasan, we already had the discussion about ginkgo in the past and explicitly decided against it. I guess we have now more maintainers onboard, which may share different thoughts.

My 2c: I would honestly prefer to avoid using Ginkgo or any other framework
that reads more like sentences but less like code.

**Comment by naveensrinivasan** [comment]
> Hey @naveensrinivasan, we already had the discussion about ginkgo in the past and explicitly decided against it. I guess we have now more maintainers onboard, which may share different thoughts.

@saschagrunert  What are the reasons for not choosing ginkgo? I looked into issues and couldn't find any information. This will help anyone understand the reasons for this explicit decision.

Thanks

**Comment by saschagrunert** [comment]
> > Hey @naveensrinivasan, we already had the discussion about ginkgo in the past and explicitly decided against it. I guess we have now more maintainers onboard, which may share different thoughts.
> 
> @saschagrunert What are the reasons for not choosing ginkgo? I looked into issues and couldn't find any information. This will help anyone understand the reasons for this explicit decision.

This was one of the first decisions we took while ramping up the project. That's why we're now using `testify`. Generally I'm open to re-evaluate the decision and switch if the majority wants to use it.

**Comment by naveensrinivasan** [comment]
> > @saschagrunert What are the reasons for not choosing ginkgo? I looked into issues and couldn't find any information. This will help anyone understand the reasons for this explicit decision.
> 
> This was one of the first decisions we took while ramping up the project and that's why we're now using `testify`. Reducing the complexity of the tests was the major argument these days.
> 
> Generally I'm open to re-evaluate the decision and switch if the majority wants to use it.

@saschagrunert Can you be specifics about what complexity you see in using `ginkgo` vs `testify`?  

Also on a similar note what are your thoughts on using https://godoc.org/sigs.k8s.io/controller-runtime/pkg/envtest? 
IMO Fakeclient are mess  https://github.com/kubernetes-sigs/controller-runtime/issues/348#issuecomment-469897122

The recommended way to test is using `envtest` without jumping through hoops and not setting up `kind` cluster for every test. Also with `e2e`, it is impossible to measure codecoverage

**Comment by naveensrinivasan** [comment]
My ignorance of not understanding the `testify`. I can see how `testify` is comparable with `ginkgo` but in a more non-bdd driven. Thanks
