### ISSUE TITLE
Further enhancements to Deployment / DaemonSet model

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#212]
This issue should collect possible enhancements to our current deployment model. Right now we create a Deployment which takes care of deploying the DaemonSet.

Context: https://docs.google.com/document/d/1mIfBJYGOcrNMnXsTw6i3jp8IYyjHC5DZkiuuufFAn_s/edit

Do you see any further enhancements which can be part of this umbrella issue?

**Comment by jhrozek** [comment]
Apart from the things already described in the document which I agree with (e.g. the capability to assess the node security policies would be nice), I wonder if the approach with the statically defined DS definition scales well. I wonder if it would be nicer to have some kind of "builder" that would dynamically add or remove containers or capabilities based on the features enabled. This might be handy when we add even more functionality to the operator and might ease on-the-fly changes to the DS based on updates or nodes with different capabilities coming up.

**Comment by saschagrunert** [comment]
We thought about a possibility to add a socket to each node to prevent the higher set of privileges within our containers. @pjbgf can you elaborate on that?
