### ISSUE TITLE
selinux: Use events in the selinux controller

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#225]
#### What would you like to be added:
decorate the selinux policy controller with events.

#### Why is this needed:
It was suggested in PR#214 that the selinux controller should use events so that admins are aware of what has happened.

**Comment by jhrozek** [comment]
@naveensrinivasan are you still planning on working on this issue?

**Comment by naveensrinivasan** [comment]
Sorry I am not planning to. Thanks
