### ISSUE TITLE
Proposal: Allow `spoc` to simultaneously record different profile types.

### ISSUE THREAD

**Issue by mhils** [kubernetes-sigs/security-profiles-operator#2255]
#### What would you like to be added:

spoc currently has `--type` and `--output-file` options for the profile that should be recorded. This means we cannot easily record Seccomp and AppArmor profiles at the same time: it's either `--type seccomp` or `--type apparmor`. It would be useful if we could record both AppArmor and Seccomp profiles at the same time. This requires some changes to the CLI interface:

1. **Option A:** Add dedicated `--apparmor`, `--apparmor-raw`, `--seccomp`, ... options. A user could run
   ```
   spoc --apparmor-raw apparmor-profile.yaml --seccomp seccomp-profile.yml ...
   ```
   to record both Seccomp and AppArmor profiles simultaneously. This would break the existing command line interface.
2. **Option B:** Make `--type` support new "combined" types such as `apparmor,seccomp` or simply a new meta type `all`. A user could run 
   ```
   spoc --type all --output-file profile.yaml ...
   ```
   to record both Seccomp and AppArmor CRD profiles simultaneously. We're limited to a single (combined) outfile.

Any thoughts/opinions? :)

**Comment by saschagrunert** [comment]
@mhils thank you for the feature proposal! I think Option B would be great to have. :+1:
