### ISSUE TITLE
OLM tests are flaking

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#2267]
The tests are flaking recently: https://github.com/kubernetes-sigs/security-profiles-operator/actions/workflows/olm_tests.yaml

We should look into them to see how to stabilize the runs.

**Comment by mhils** [comment]
I've started making things more robust in https://github.com/kubernetes-sigs/security-profiles-operator/pull/2274 and will continue until I get a passing run. 😅

**Comment by saschagrunert** [comment]
@mhils do you think we can close this one now?

**Comment by mhils** [comment]
Yes, let's close this!
