### ISSUE TITLE
Update kubectl command in security-profiles-operator documentation

### ISSUE THREAD

**Issue by Aaina26** [kubernetes-sigs/security-profiles-operator#2321]
#### What happened:
While investigating the following issue: https://github.com/kubernetes/kubernetes/issues/125526 I found an issue with a command under https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/installation-usage.md#create-an-apparmor-profile
This command: `kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"enableAppArmor":"true"}}'` should produce this output `securityprofilesoperatordaemon.security-profiles-operator.x-k8s.io/spod patched`. But it produces this output instead `The SecurityProfilesOperatorDaemon "spod" is invalid: spec.enableAppArmor: Invalid value: "string": spec.enableAppArmor in body must be of type boolean: "string"`

#### Solution:
replace the command with this command instead: `kubectl -n security-profiles-operator patch spod spod --type=merge -p '{"spec":{"enableAppArmor":true}}'`
Running this resolves the issue and gives the expected output.

**Comment by saschagrunert** [comment]
Thank you for the report @Aaina26, a fix is landing in #2322 .
