### ISSUE TITLE
go lint failures on macos

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes-sigs/security-profiles-operator#235]
#### What happened:
The `make verify-go-lint` fails on macos.
`ERRO Running error: buildir: failed to load package : could not load export data: no export data for "github.com/seccomp/libseccomp-golang"`

#### What you expected to happen:
Should not fail on macos.

#### How to reproduce it (as minimally and precisely as possible):
`make verify-go-lint`
https://github.com/naveensrinivasan/security-profiles-operator/runs/1765263186?check_suite_focus=true

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
I think it tries to include the seccomp build tag which fails on macOS: 
https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/.golangci.yml#L7
