### ISSUE TITLE
No ApparmorProfile available in CRD  profilerecordings.security-profiles-operator.x-k8s.io 

### ISSUE THREAD

**Issue by Jeansen** [kubernetes-sigs/security-profiles-operator#2363]
#### What happened:
I installed SPO 0.8.4 via OLM and followed the documentation regarding an example installation of a ProfileRecording. I am running Kubernetes 1.30.0. I had a look at the examples and wanted to try recording for AppArmor. But I get `The ProfileRecording "test-recording" is invalid: spec.kind: Unsupported value: "ApparmorProfile": supported values: "SeccompProfile", "SelinuxProfile"`

#### What you expected to happen:
I'd have expected the ProfileRecording to  be valid and accepted.

#### How to reproduce it (as minimally and precisely as possible):
- Install latest SPO via OLM
-  `kubectl -n security-profiles-operator  patch spod spod --type=merge -p '{"spec":{"enableAppArmor":true}}'`
- `kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/bb3a48e92a9d7e43fc3c966cb660be70abe8d572/examples/profilerecording-apparmor-bpf.yaml`

#### Anything else we need to know?:
I had a look at the CRD `kubectl get crd profilerecordings.security-profiles-operator.x-k8s.io -o yaml`

And there I see:

```
  kind:
    description: Kind of object to be recorded.
    enum:
    - SeccompProfile
    - SelinuxProfile
    type: string

```
So, I wonder why the ApparmorProfile is no listet in the Enum? With this CRD it is currently not possible (or I am missing something) to create a ProfileRecording with `spec.kind: ApparmorProfile`.

I also had a look at https://github.com/kubernetes-sigs/security-profiles-operator/blob/bb3a48e92a9d7e43fc3c966cb660be70abe8d572/hack/ci/e2e-apparmor.sh to but could not see what I might have been missing ...

#### Environment:

- Cloud provider or hardware configuration: QEMU/KVM
- OS (e.g: `cat /etc/os-release`): Debian 12
- Kernel (e.g. `uname -a`): Host, running Node VMs: `Linux cluster 6.8.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.8.12-1 (2024-05-31) x86_64 GNU/Linux`

- Others: 
Kuberntes 1.30.0. Nodes created with QEMU/KVM. Example Kernel vom Master0 Node: `Linux master0-k8s.lan 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux`

**Comment by saschagrunert** [comment]
cc @ccojocar

**Comment by ccojocar** [comment]
@Jeansen This is fixed in master. We added e2e tests here https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/hack/ci/e2e-apparmor.sh. It should be available in the next release.

**Comment by Jeansen** [comment]
Kudos! :-)
