### ISSUE TITLE
seccomp: audit logs enrichment

### ISSUE THREAD

**Issue by pjbgf** [kubernetes-sigs/security-profiles-operator#244]
#### What would you like to be added:

Enrich seccomp logs with Kubernetes data (i.e. `namespace`, `pod` and `container`) and potentially outcome (e.g. `blocked`/`allowed`).

#### Why is this needed:

In a cluster and at scale, the built-in audit logs for seccomp are hard to track back to specific pods/containers.
The existing logs:

`[252130.031583] audit: type=1326 audit(1611996299.149:466250): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=615549 comm="sh" exe="/bin/busybox" sig=0 arch=c000003e syscall=1 compat=0 ip=0x7f61a81c5923 code=0x7ffc0000`

Initial suggested enriched logs format:
`audit(1611996299.149:466250) type=seccomp node=kube-worker1 pid=20923 ns=default pod=my-pod c=container1 exe=/init syscall=epoll_pwait`

**Comment by saschagrunert** [comment]
Yeah this looks like a great enhancement. How would you implement it from a technical perspective? Would it work on every Linux machine?

**Comment by pjbgf** [comment]
Yes, I got it already working for Ubuntu and CRI-O. Need to test it a bit better but I believe it would not be a problem to support other distros (CentOS and RedHat) and container runtimes.

One question I have is whether it is worth having that in-tree (including the generation of a new docker image), if so keen on creating that PR today.

@JAORMX does SELinux also generate audit logs on "complain-mode"?

**Comment by JAORMX** [comment]
@pjbgf it does generate audit logs, both in "enforcing" and "permissive" mode (which I guess is similar to "complain-mode").

**Comment by cmurphy** [comment]
/close

This was done in https://github.com/kubernetes-sigs/security-profiles-operator/pull/279 https://github.com/kubernetes-sigs/security-profiles-operator/pull/251 https://github.com/kubernetes-sigs/security-profiles-operator/pull/339
