### ISSUE TITLE
add daemonset resource requests to Helm chart

### ISSUE THREAD

**Issue by gsstuart** [kubernetes-sigs/security-profiles-operator#2455]
#### What would you like to be added:
Add daemonset resource requests to the Helm values, as an alternative to the [patch approach](https://github.com/kubernetes-sigs/security-profiles-operator/blob/v0.8.4/installation-usage.md#customise-the-daemon-resource-requirements) currently recommended in the docs.
#### Why is this needed:
With the default daemonset memory limits, it OOM-loops on larger clusters, and having to do a `kubectl patch` -- especially since the daemonset is not created by the Helm chart itself -- is awkward when deploying with something like Argo.

**Comment by saschagrunert** [comment]
@gsstuart thank you for the request. Do you consider to contribute the change by yourself?

**Comment by gsstuart** [comment]
Hi @saschagrunert!  Sure thing... I'm currently implementing the change in an internal fork, and would be happy to contribute back once it's looking good.
