### ISSUE TITLE
BPF Recorder doesn't work on Rancher Desktop

### ISSUE THREAD

**Issue by aliaksxssv** [kubernetes-sigs/security-profiles-operator#2483]
#### What happened:

BPF Recorder container doesn't start

#### What you expected to happen:

BPF Recorder container is running

#### How to reproduce it (as minimally and precisely as possible):

I use Rancher Desktop for Mac OS v 1.16.0

#### Environment:

Hardware OS: macOS Sonoma 14.5

Virtual Environment: Rancher Desktop v 1.16.0 - Kubernetes version 1.25, Container Engine dockerd (Moby)

**$ rdctl shell**
**# uname -r** 
6.6.51-0-virt

**$ kubectl logs spod-gpxnq -c bpf-recorder -n security-profiles-operator**
libbpf: prog 'sys_enter': relo #0: patched insn #0 (LDX/ST/STX) off 8 -> 8
libbpf: prog 'sys_enter': relo #1: <byte_off> [316] struct task_struct.nsproxy (0:125 @ offset 2664)
libbpf: prog 'sys_enter': relo #1: matching candidate #0 <byte_off> [160] struct task_struct.nsproxy (0:124 @ offset 2584)
libbpf: prog 'sys_enter': relo #1: patched insn #5 (ALU/ALU64) imm 2664 -> 2584
libbpf: prog 'sys_enter': relo #2: <byte_off> [566] struct nsproxy.mnt_ns (0:3 @ offset 24)
libbpf: prog 'sys_enter': relo #2: matching candidate #0 <byte_off> [511] struct nsproxy.mnt_ns (0:3 @ offset 24)
libbpf: prog 'sys_enter': relo #2: patched insn #13 (ALU/ALU64) imm 24 -> 24
libbpf: prog 'sys_enter': relo #3: <byte_off> [573] struct mnt_namespace.ns.inum (0:0:2 @ offset 16)
libbpf: prog 'sys_enter': relo #3: matching candidate #0 <byte_off> [3664] struct mnt_namespace.ns.inum (0:0:2 @ offset 16)
libbpf: prog 'sys_enter': relo #3: patched insn #19 (ALU/ALU64) imm 16 -> 16
libbpf: map 'events': created successfully, fd=8
libbpf: map 'child_pids': created successfully, fd=9
libbpf: map 'active_pids': created successfully, fd=10
libbpf: map 'mntns_syscalls': created successfully, fd=11
libbpf: map 'recorder.rodata': created successfully, fd=12
libbpf: map 'recorder.bss': created successfully, fd=13
libbpf: prog 'file_open': failed to find kernel BTF type ID of 'file_open': -3
libbpf: prog 'file_open': failed to prepare load attributes: -3
libbpf: prog 'file_open': failed to load: -3
libbpf: failed to load object 'recorder.bpf.o'
E1005 07:18:18.487778   13933 main.go:238] "running security-profiles-operator" err="load self-test: load bpf object: failed to load BPF object: no such process" logger="setup"

**Comment by ccojocar** [comment]
It seems that eBPF is not supported. It supports only the following Linux distributions: Ubuntu/Debian/Fedora/Flatcar.
