### ISSUE TITLE
LOCALHOSTPROFILE empty  - Unable to install any SeccompProfile

### ISSUE THREAD

**Issue by emzxcv** [kubernetes-sigs/security-profiles-operator#2498]
#### What happened:
I installed SOP via Helm. 
`helm install security-profiles-operator --namespace security-profiles-operator https://github.com/kubernetes-sigs/security-profiles-operator/releases/download/v0.8.4/security-profiles-operator-0.8.4.tgz`

![image](https://github.com/user-attachments/assets/1a069c8e-1efc-4226-9f8f-e204f4ac9776)

#### What you expected to happen:
LOCALHOSTPROFILE should be populated so it can be referenced by pods as the LocalhostProfile field.

#### How to reproduce it (as minimally and precisely as possible):
Just install SOP 0.8.4, create a seccompprofile resource in the SAME namespace. It should create but never reach any status of 'Installed' and LOCALHOSTPROFILE is empty.  

#### Anything else we need to know?:
I have tried creating in default namespace and the security-profiles-operator where i installed SOP. Both do not work. 

Two of the 3 pods seem to have this log:

![image](https://github.com/user-attachments/assets/317f6608-5215-4fea-9d42-f8af229801c2)
#### Environment:

- Cloud provider or hardware configuration: GKE 
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Others:

**Comment by ccojocar** [comment]
It should be hopefully fixed in the next release for GKE https://github.com/kubernetes-sigs/security-profiles-operator/pull/2541 but I haven't tried helm.
