### ISSUE TITLE
Deploy ProfileBinding/ProfileRecording webhook as a configurable addon option

### ISSUE THREAD

**Issue by cmurphy** [kubernetes-sigs/security-profiles-operator#270]
Currently the `Deployment` that handles the `ProfileBinding` and `ProfileRecording` webhook as well as the controllers for those CRDs is applied manually via the `webhook.yaml` manifest. Conversely, the DaemonSet controllers are configured and launched by the operator. We should follow the same pattern with the webhook configuration and eliminate the `webhook.yaml` manifest.

This relates to the discussion of the deployment model in #212. See also #237 where the new manifest file was added.

**Comment by saschagrunert** [comment]
Hey @cmurphy, are you planning to work on this one? :blush:

**Comment by cmurphy** [comment]
I can work on it, but not this week

**Comment by saschagrunert** [comment]
@cmurphy do you still wanna take this one or would you need support? :)

**Comment by cmurphy** [comment]
@saschagrunert I'm working on it as we speak :)
