### ISSUE TITLE
Introduce metrics for the operator

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#276]
We should think about a metrics endpoint which provides aggregated data. For example we could provide the amount of errored policies, which is more useful for SRE's than debugging events.

**Comment by saschagrunert** [comment]
Follow-ups of #422:
- decide which metrics we would like to implement
- provide documentation around the feature
- add metric related e2e tests
- integrate controller-runtime metris: https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html (currently served on :8080 per default)
- secure the metrics via tls and authentication (maybe via an auth proxy or directly within the implementation)

**Comment by jhrozek** [comment]
@saschagrunert We're interested in adding some metrics for the SELinux part. Would you prefer a separate ticket or just as part of this one. Of course we're going to do the work :-) I'm just asking about the issue.

**Comment by saschagrunert** [comment]
> @saschagrunert We're interested in adding some metrics for the SELinux part. Would you prefer a separate ticket or just as part of this one. Of course we're going to do the work :-) I'm just asking about the issue.

Sure, let's do it as part of this issue, too. :+1:

**Comment by saschagrunert** [comment]
This is done for now.
