### ISSUE TITLE
Multi-architecture support

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#282]
The idea is to build a multi-architecture image to support a common set of golang architectures (linux-only for now).

Question: For which kind of architectures do we see a benefit if we decide to implement that feature?

**Comment by jhrozek** [comment]
> The idea is to build a multi-architecture image to support a common set of golang architectures (linux-only for now).
> 
> Question: For which kind of architectures do we see a benefit if we decide to implement that feature?

What about arm64 to support both Apple M1 and RPi4?
What about e2e, IIRC kind is x86_64 only?

**Comment by jhrozek** [comment]
> > The idea is to build a multi-architecture image to support a common set of golang architectures (linux-only for now).
> > Question: For which kind of architectures do we see a benefit if we decide to implement that feature?
> 
> What about arm64 to support both Apple M1 and RPi4?
> What about e2e, IIRC kind is x86_64 only?

Sorry to reply to myself, but just to be clear: When I say Apple M1 I meant mostly to support kind running on that HW, or a arch64 VM that's backing something like minikube etc..

**Comment by saschagrunert** [comment]
Yes, I think focussing on arm64 for now should be a good starting point :+1:
