### ISSUE TITLE
Consider removing the `targetWorkload` field for seccomp profiles

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#347]
We could think about removing the `targetWorkload` field from the seccomp profile CRD. Do we really need it? During development it was mostly confusing to have another sub-path in the whole local path.

Let's evaluate what we would break when removing it.

**Comment by cmurphy** [comment]
Sorry to jump on this late, just wanted to note for posterity that this is why we added it in the first place: https://github.com/kubernetes-sigs/security-profiles-operator/pull/138#issuecomment-705989431

With the way `ProfileBinding` binds to images and not workload tags I agree we don't need this anymore.
