### ISSUE TITLE
Autodetect or build-time select platform capabilities

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#369]
#### What would you like to be added:
Autodetect and/or select during build with build flags the capabilities of the k8s platform - does it support seccomp? Does it suport SELinux?

This could take several forms:
 - just allow the "packager" to select the defaults with build-time flags
 - check the k8s distro type. This could be something like try an API discovery for a proprietary OpenShift object and if we detect that the platform is OpenShift, enable SELinux by default
 - on startup, run a pod with the same nodeSelector as the SPOD DS, the pod would probe one of the nodes (for selinux, the probe could be as easy as `stat(/sys/fs/selinux`)
 - ditto for the SPOD pods themselves to avoid reconciling a resource on platforms that don't support that security profile type. There is already a stub of such check in seccomp, but it unconditionally returns true.

#### Why is this needed:
To avoid issues like PR#368

#### User story covered
As an application SRE, Rajesh would like to deploy a Seccomp profile and an SELinux or AppArmor profiles to secure their application.

**Comment by saschagrunert** [comment]
Side node, for seccomp we already have this:
https://github.com/kubernetes-sigs/security-profiles-operator/blob/cb86d7ba15f5a4961ab64cefe7a15797965a845d/internal/pkg/daemon/seccompprofile/seccompprofile.go#L174-L188

I agree that it would be useful to have for SELinux. :+1:
