### ISSUE TITLE
Reconcile per-node statuses using a separate status reconciler

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#373]
#### What happened:
Even though the per-node statuses decrease the amount of races and make the statuses more dependable, it is only /mostly/ the case. As proposed in PR #361, the reconcile loop in the DS pods primarily managers the per-node statuses and if all per-node statuses agree, the same reconcile loop also updates the global policy status.

This has two problems:
 - we still have concurrent access to a shared resource and thus we get conflicts. This is irritating, but not unsolvable
 - the current algorithm to update the global policy status is simplistic, just list all the other per-node statuses and if they all are the same, update the global status. But the problem occurs if the other per-node statuses /are not created yet at all/. This is especially a problem for the seccomp reconcile loop that is very fast and just dumps a file onto the filesystem.

An example of the race might be:
 - two nodes A and B, A is very fast and managers to reconcile a seccomp profile all the way to it being installed before the reconciler on B even picks up the reconcile loop
 - A goes to installing, the pod on A does a list and finds only node-status A, thinks all nodes are 'consistent' and sets the global status as installed
 - later on B picks up the reconciliation and installs the policy, but before that a pod can theoretically be deployed on B that tries to reference that policy

#### What you expected to happen:
Race-free SPO statuses. I propose we add a new controller that only synchronizes the statuses. It could reconcile on changes to nodeStatus, list all the pods in a DS that manages the policy and only if all pods in the DS actually have a state, act on the state change.

This might have the following benefits:
 - there is exactly one place that writes to the node statuses, which means fewer races
 - a separate reconcile loop feels like a better way to observe a status of a DS than a pod running within the DS itself
 - the DS pods would no longer need write access to the policy object statuses, only to the node statuses
 - the code could potentially be better shared between policy controllers

#### How to reproduce it (as minimally and precisely as possible):
Not very often with the node statuses, but occasionally reproduces in e2e tests with seccomp.

#### Anything else we need to know?:
This is not a fully fleshed out idea, comments or alternative solutions welcome.

**Comment by jhrozek** [comment]
In case I need to disappear this week, I'm pushing my progress here: https://github.com/jhrozek/security-profiles-operator/tree/status_ctrl

**Comment by JAORMX** [comment]
/assign

Taking over this work as @jhrozek is not available for some days.
