### ISSUE TITLE
Create plan about graduating APIs

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#407]
All our internal APIs (CRDs) are in `alpha` right now. We also follow a pre v1.x.y semver scheme right now, which allows us breaking the API as we want.

If we want to integrate the operator in more conservative projects, then we may wanna graduate our APIs and move to a v1.x.y release scheme.

This means: 
- We should draft a plan how we want to graduate our APIs.
- We should discuss if this API graduation fits to our 0.x.y versioning model.

Ref: https://github.com/openshift/enhancements/pull/745#discussion_r616771358

**Comment by jhrozek** [comment]
As a quick note, issue #223 would still change the API to include the error message. But in general I agree about the need to have a plan.
