### ISSUE TITLE
Could not delete seccomp profile

### ISSUE THREAD

**Issue by tshaiman** [kubernetes-sigs/security-profiles-operator#413]
#### What happened:
after applying the seccomp profile on several pods, after removing the pods , tried to delete the profile 

got an hanging message in the terminal  :"seccompprofile.security-profiles-operator.x-k8s.io "my-profile" deleted"
but it never retruns and the profile did not delete.

#### What you expected to happen:
profile should be removed as with any other k8s resource.

#### How to reproduce it (as minimally and precisely as possible):
try to delete an exiting propfile
#### Anything else we need to know?:
- AKS
- k version 1.19
#### Environment:

- Cloud provider or hardware configuration: Azure AKS Version 1.19 , Linux node pool
- OS (e.g: `cat /etc/os-release`): Linux
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by saschagrunert** [comment]
Hey @tshaiman :wave:, thank you for submitting the issue report.

Indeed, this should not happen. We apply a finalizer to every profile if there are any active workloads around, which may block the deletion in your case. Can you provide us the logs of the operator deamon and the output of the `kubectl decribe my-profile` command? :)

**Comment by jhrozek** [comment]
I would also like to ask what is the version of the operator. If you're running an older released version, I would recommend to try out 0.3.0 which is being released right now. Quite a lot of fixes and changes went into this version..

**Comment by tshaiman** [comment]
i’m on the latest from yesterday

**Comment by tshaiman** [comment]
1. i could not delete it even when no workload uses it yet.

2. what in case of the following scenario :
- create profile 
- create workload
- delete workload / remove the seccomp from it

bug: the profile stil “thinks” there is workload and could not be deleted

**Comment by tshaiman** [comment]
--below is the output from the 'kubectl describe profile' command , it had
ALL the node names (more than 40) as its finalizers , but in actual there
was not a single pod that used that profile YET !

Name:         aed-profile
Namespace:    my-ns
Labels:       <none>
Annotations:  <none>
API Version:  security-profiles-operator.x-k8s.io/v1alpha1
Kind:         SeccompProfile
Metadata:
  Creation Timestamp:  2021-04-25T15:21:06Z
  Finalizers:
    aks-primary-33447832-vmss000000-delete
    aks-fe-33447832-vmss000000-delete
    aks-fe1-33447832-vmss000001-delete
    aks-fe-33447832-vmss000001-delete
    aks-algo1-33447832-vmss000000-delete
    aks-algo1-33447832-vmss000001-delete
    aks-primary-33447832-vmss000001-delete
    aks-fe1-33447832-vmss000000-delete
    aks-algo1-33447832-vmss000002-delete
    aks-algo1-33447832-vmss000003-delete
    aks-algo-33447832-vmss000001-delete
    aks-algo-33447832-vmss000000-delete
    aks-algo-33447832-vmss000002-delete
    aks-algo-33447832-vmss000003-delete
    aks-algo-33447832-vmss000006-delete
    aks-algo-33447832-vmss00000a-delete
    aks-algo-33447832-vmss00000b-delete
    aks-algo-33447832-vmss000009-delete
    aks-algo-33447832-vmss000004-delete
    aks-algo-33447832-vmss000008-delete
    aks-algo-33447832-vmss000005-delete
    aks-algo-33447832-vmss000007-delete
    aks-algo-33447832-vmss00000c-delete
    aks-algo-33447832-vmss00000d-delete
    aks-algo-33447832-vmss00000e-delete
    aks-algo-33447832-vmss00000f-delete
    aks-algo-33447832-vmss00000i-delete
    aks-algo-33447832-vmss00000j-delete
    aks-algo-33447832-vmss00000t-delete
    aks-algo-33447832-vmss00000p-delete
    aks-algo-33447832-vmss00000n-delete
    aks-algo-33447832-vmss00000u-delete
    aks-algo-33447832-vmss00000q-delete
    aks-algo-33447832-vmss00000m-delete
    aks-algo-33447832-vmss00000k-delete
    aks-algo-33447832-vmss00000r-delete
    aks-algo-33447832-vmss00000h-delete
    aks-algo-33447832-vmss00000s-delete
    aks-algo-33447832-vmss00000g-delete
    aks-algo-33447832-vmss00000l-delete
    aks-algo-33447832-vmss00000o-delete
    aks-algo-33447832-vmss00000v-delete
  Generation:  1
  Managed Fields:
    API Version:  security-profiles-operator.x-k8s.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:defaultAction:
        f:syscalls:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-04-25T15:21:06Z
    API Version:  security-profiles-operator.x-k8s.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"aks-algo-33447832-vmss000000-delete":
          v:"aks-algo-33447832-vmss000001-delete":
          v:"aks-algo-33447832-vmss000002-delete":
          v:"aks-algo-33447832-vmss000003-delete":
          v:"aks-algo-33447832-vmss000004-delete":
          v:"aks-algo-33447832-vmss000005-delete":
          v:"aks-algo-33447832-vmss000006-delete":
          v:"aks-algo-33447832-vmss000007-delete":
          v:"aks-algo-33447832-vmss000008-delete":
          v:"aks-algo-33447832-vmss000009-delete":
          v:"aks-algo-33447832-vmss00000a-delete":
          v:"aks-algo-33447832-vmss00000b-delete":
          v:"aks-algo-33447832-vmss00000c-delete":
          v:"aks-algo-33447832-vmss00000d-delete":
          v:"aks-algo-33447832-vmss00000e-delete":
          v:"aks-algo-33447832-vmss00000f-delete":
          v:"aks-algo-33447832-vmss00000g-delete":
          v:"aks-algo-33447832-vmss00000h-delete":
          v:"aks-algo-33447832-vmss00000i-delete":
          v:"aks-algo-33447832-vmss00000j-delete":
          v:"aks-algo-33447832-vmss00000k-delete":
          v:"aks-algo-33447832-vmss00000l-delete":
          v:"aks-algo-33447832-vmss00000m-delete":
          v:"aks-algo-33447832-vmss00000n-delete":
          v:"aks-algo-33447832-vmss00000o-delete":
          v:"aks-algo-33447832-vmss00000p-delete":
          v:"aks-algo-33447832-vmss00000q-delete":
          v:"aks-algo-33447832-vmss00000r-delete":
          v:"aks-algo-33447832-vmss00000s-delete":
          v:"aks-algo-33447832-vmss00000t-delete":
          v:"aks-algo-33447832-vmss00000u-delete":
          v:"aks-algo-33447832-vmss00000v-delete":
          v:"aks-algo1-33447832-vmss000000-delete":
          v:"aks-algo1-33447832-vmss000001-delete":
          v:"aks-algo1-33447832-vmss000002-delete":
          v:"aks-algo1-33447832-vmss000003-delete":
          v:"aks-fe-33447832-vmss000000-delete":
          v:"aks-fe-33447832-vmss000001-delete":
          v:"aks-fe1-33447832-vmss000000-delete":
          v:"aks-fe1-33447832-vmss000001-delete":
          v:"aks-primary-33447832-vmss000000-delete":
          v:"aks-primary-33447832-vmss000001-delete":
      f:status:
        .:
        f:conditions:
        f:localhostProfile:
        f:status:
    Manager:         security-profiles-operator
    Operation:       Update
    Time:            2021-04-26T11:49:40Z
  Resource Version:  658968
  Self Link:         /apis/
security-profiles-operator.x-k8s.io/v1alpha1/namespaces/my-ns/seccompprofiles/aed-profile
  UID:               cb1da1cd-eb7a-4150-bc0c-8b088060474f
Spec:
  Default Action:  SCMP_ACT_ERRNO
  Syscalls:
    Action:  SCMP_ACT_ALLOW
    Names:
      exit_group
      access

...... list of all Seccomp profile we have been using (approx 50 entries)
      shutdown
Status:
  Conditions:
    Last Transition Time:  2021-04-25T15:24:03Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Localhost Profile:       operator/my-ns/aed-profile.json
  Status:                  Installed
Events:                    <none>

**Comment by tshaiman** [comment]
in addition I would like to note that the security-profile-operator itself
, cannot be removed and is hanging in "terminating" mode for few days :

[image: image.png]

**Comment by tshaiman** [comment]
another issue is that other pods , not related to Sec-comp cannot be
removed now and are sending the following error :

warning: Immediate deletion does not wait for confirmation that the running
resource has been terminated. The resource may continue to run on the
cluster indefinitely.
Error from server (InternalError): Internal error occurred: failed calling
webhook "binding.spo.io": Post "
https://webhook-service.security-profiles-operator.svc:443/mutate-v1-pod-binding?timeout=10s":
service "webhook-service" not found

**Comment by jhrozek** [comment]
On Mon, Apr 26, 2021 at 08:13:56AM -0700, Tomer Shaiman wrote:
> 1. i could not delete it even when no workload uses it yet.
> 
> 2. what in case of the following scenario :
> - create profile 
> - create workload
> - delete workload / remove the seccomp from it
> 
> bug: the profile stil “thinks” there is workload and could not be deleted 

I don't think this is the case because I don't see either
.status.activeWorkloads or the 'in-use-by-active-pods' finalizer.

**Comment by jhrozek** [comment]
On Mon, Apr 26, 2021 at 01:11:35PM -0700, Tomer Shaiman wrote:
> --below is the output from the 'kubectl describe profile' command , it had
> ALL the node names (more than 40) as its finalizers , but in actual there
> was not a single pod that used that profile YET !

This is expected. The node finalizers act as a guard so that the profile
object is not deleted until the seccomp profiles on individual nodes
are.

> 
> Name:         aed-profile
> Namespace:    my-ns
> Labels:       <none>
> Annotations:  <none>
> API Version:  security-profiles-operator.x-k8s.io/v1alpha1
> Kind:         SeccompProfile
> Metadata:
>   Creation Timestamp:  2021-04-25T15:21:06Z
>   Finalizers:
>     aks-primary-33447832-vmss000000-delete
>     aks-fe-33447832-vmss000000-delete
>     aks-fe1-33447832-vmss000001-delete
>     aks-fe-33447832-vmss000001-delete
>     aks-algo1-33447832-vmss000000-delete
>     aks-algo1-33447832-vmss000001-delete
>     aks-primary-33447832-vmss000001-delete
>     aks-fe1-33447832-vmss000000-delete
>     aks-algo1-33447832-vmss000002-delete
>     aks-algo1-33447832-vmss000003-delete
>     aks-algo-33447832-vmss000001-delete
>     aks-algo-33447832-vmss000000-delete
>     aks-algo-33447832-vmss000002-delete
>     aks-algo-33447832-vmss000003-delete
>     aks-algo-33447832-vmss000006-delete
>     aks-algo-33447832-vmss00000a-delete
>     aks-algo-33447832-vmss00000b-delete
>     aks-algo-33447832-vmss000009-delete
>     aks-algo-33447832-vmss000004-delete
>     aks-algo-33447832-vmss000008-delete
>     aks-algo-33447832-vmss000005-delete
>     aks-algo-33447832-vmss000007-delete
>     aks-algo-33447832-vmss00000c-delete
>     aks-algo-33447832-vmss00000d-delete
>     aks-algo-33447832-vmss00000e-delete
>     aks-algo-33447832-vmss00000f-delete
>     aks-algo-33447832-vmss00000i-delete
>     aks-algo-33447832-vmss00000j-delete
>     aks-algo-33447832-vmss00000t-delete
>     aks-algo-33447832-vmss00000p-delete
>     aks-algo-33447832-vmss00000n-delete
>     aks-algo-33447832-vmss00000u-delete
>     aks-algo-33447832-vmss00000q-delete
>     aks-algo-33447832-vmss00000m-delete
>     aks-algo-33447832-vmss00000k-delete
>     aks-algo-33447832-vmss00000r-delete
>     aks-algo-33447832-vmss00000h-delete
>     aks-algo-33447832-vmss00000s-delete
>     aks-algo-33447832-vmss00000g-delete
>     aks-algo-33447832-vmss00000l-delete
>     aks-algo-33447832-vmss00000o-delete
>     aks-algo-33447832-vmss00000v-delete

[...]

> Status:
>   Conditions:
>     Last Transition Time:  2021-04-25T15:24:03Z
>     Reason:                Available
>     Status:                True
>     Type:                  Ready
>   Localhost Profile:       operator/my-ns/aed-profile.json
>   Status:                  Installed
> Events:                    <none>

Hmm, I find it strange that there are no events, I would have expected
at least an event that says that the profile is installed..

**Comment by jhrozek** [comment]
Would you mind tailing the logs of the SPO itself (the pod in the deployment) as well as one of the DS pods to see if any reports surface from there?

**Comment by jmcshane** [comment]
I'm running into the same issue on EKS. I can provide some debug information from my installation. I've tried reinstalling the security-profiles-operator to ensure the finalizer can complete, but unfortunately the cluster appears to be completely stuck.

**Comment by saschagrunert** [comment]
Yeah @jmcshane some log as @jhrozek mentioned would be good and a reproducer if possible.

**Comment by jmcshane** [comment]
ok @saschagrunert, i figured out my problem. since i had deleted the operator, i manually removed the finalizer on the CRD objects to allow them to delete. this allowed me to get my cluster back to the previous state.

definitely had to review the uninstall docs before uninstalling: https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/installation-usage.md#uninstalling

I don't think there's an active issue here, just an explicit uninstall order that's enforced by the finalizer on the profiles CRD objects.

**Comment by saschagrunert** [comment]
Thank you for the clarification @jmcshane? Feel free to provide further input if the issue or something similar occurs again. :blush:

**Comment by longpi1** [comment]
> [https://webhook-service.securit](https://webhook-service.security-profiles-operator.svc:443/mutate-v1-pod-binding?timeout=10s)

I also have this problem. Is there any way to solve it
