### ISSUE TITLE
Milestone v0.4.0 planning

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#418]
Let's collect a list of things we would like to address for the next milestone (I named it 0.4.0, which may change).

Things on top of my mind:
- API graduation plan (https://github.com/kubernetes-sigs/security-profiles-operator/issues/407)
- Initial metrics implementation (https://github.com/kubernetes-sigs/security-profiles-operator/issues/276)
- Replacing the namespaced operator deployment variant (https://github.com/kubernetes-sigs/security-profiles-operator/issues/199)

Feel free to drop your thoughts that we get a feeling about what we want/can achieve in the next couple of months. :raised_hands:

**Comment by saschagrunert** [comment]
cc @cmurphy @JAORMX @jhrozek @kubernetes-sigs/security-profiles-operator-maintainers

**Comment by JAORMX** [comment]
I'd like to achieve feature parity between Seccomp and Selinux profiles. e.g. being able to do bindings and recordings for SELinux profiles as we can with Seccomp profiles.
