### ISSUE TITLE
Add liveness/startup probe for SELinux controller

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#442]
We introduced a startup and liveness probe for the seccomp controller in #430. The same should be now done for the SPOD SELinux controller by reusing the existing infrastructure.

Refers to #443

**Comment by jhrozek** [comment]
Addressed by https://github.com/kubernetes-sigs/security-profiles-operator/commit/9679758aa1157e5bd674bed4d96dcd21dacee806

**Comment by jhrozek** [comment]
Hmm for some reason I don't see the close button, but this issue can be considered done.

**Comment by saschagrunert** [comment]
@jhrozek you should be able to do 
/reopen
