### ISSUE TITLE
Run log enricher as part of the daemon

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#467]
This allows us re-using the metrics endpoint from the daemon and create metrics for the log enrichment feature. Right now the enricher runs in a dedicated container:

https://github.com/kubernetes-sigs/security-profiles-operator/blob/12d2a6a26d06695506c81ebe5122a6d49ede4082/internal/pkg/manager/spod/bindata/spod.go#L357-L399

**Comment by JAORMX** [comment]
@jhrozek @saschagrunert this would also be useful for selinux profile recording, as we could gather those audit logs and pass them to [udica](https://github.com/containers/udica) to add any missing rules to the generated profile.

**Comment by saschagrunert** [comment]
Obsolete now
