### ISSUE TITLE
SELinux profile recording

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#476]
#### What would you like to be added:
A way for a workload to record a SELinux profile, like we record a seccomp profile

#### Why is this needed:
At the moment, users need to hand-craft SELinux profiles

#### User story covered
As an application developer, Ming would like to be able to automatically generate initial security profiles that are specific to the application.

**Comment by jhrozek** [comment]
The proposal is to use Udica for the recording.

**Comment by saschagrunert** [comment]
Sounds good to me, would recording via log-enrichment be an option, too?

**Comment by JAORMX** [comment]
@saschagrunert udica is able to read the audit logs via the `--append` command line parameter. With those audit logs, it can fill any rules that were missed from the initial generation. So, the log-enrichment feature could be used to provide those logs to Udica.

**Comment by jhrozek** [comment]
Started working on this (with some pauses due to summertime vacations..) and realized I never updated the initial high-level plan..so going to drop the current plan here in case someone wants to stop me.

After a bit of research and experimentation, I don't think we need (or want..) to use udica for the recording itself. The [parsing logic](https://github.com/containers/udica/blob/main/udica/parse.py#L186) is one function. Also udica doesn't seem to filter out duplicates which should be fixable, but still. We might need to use udica for bootstrapping of the selinux policy (what mounts does the container use, what ports, ...) or re-implement that ourselves, too. I think this would be determined during the development.

For retrieving the AVCs, I'm using a single permissive domain as Sasha suggested and parsing the container<->process relationship as the enricher already does.

I'll extend the ProfileRecordingKind to let it record SELinux, but only through the enricher interface (in general ProfileRecording also allows the use of a hook which is not possible with SELinux).

I haven't worked with GRPC much previously, so the I'll be very fuzzy here, but the high-level plan is to extend the GRPC interface to also be able to stream SELinux policy lines and collect them in the profilerecorder like we collect syscalls for seccomp profiles.
