### ISSUE TITLE
ossf scorecard: Branch-Protection

### ISSUE THREAD

**Issue by pjbgf** [kubernetes-sigs/security-profiles-operator#660]
#### Description:

This issue is to drive discussion around the ossf scorecard results for the [Branch-Protection] section. This is part of improving the project's security posture #653.

The [Branch-Protection] section of the ossf scorecard highlights the hardening recommendations for GitHub branches. Some of them may conflict with parts of our CI/CD automation, which may mean we won't be able to mitigate. 

Result: `branch protection is not maximal on development and all release branches`
Details: 

1. - [x] Linear history disabled on branch 'main' 
2. - [x] Status checks for merging disabled on branch 'main' 
3. - [x] Stale review dismissal disabled on branch 'main' 
4. - [x] Number of required reviewers is only 0 on branch 'main' 
5. - [x] Owner review not required on branch 'main' 
6. - [x] 'administrator' PRs are exempt from reviews on branch 'main'    

[Branch-Protection]: https://github.com/ossf/scorecard/blob/4fbd0fe93ec800e42fddf6a66a39298c76a829bb/docs/checks.md#branch-protection

**Comment by pjbgf** [comment]
@saschagrunert here's my views/questions on the 6 points:

1. I can't think of any issues enabling linear history for the master branch. What do you think?
2. This is a `false positive`, as status checks are enabled for `master`. No action required here.
3. The state dismissal can be a problem for us whilst we have some long running/flake tests. I think we could keep as is and review it after further improvements on test suite.
4. / 5. / 6. This may be due to the fact that "Include Administrators" is disabled - probably the same is for number 2. Do you think doing the below may break our merge automation?
    - Enable `Include Administrators`
    - Enable `Require a pull request before merging`
    - Add `k8s-ci-robot` to `Restrict who can push to matching branches`

**Comment by saschagrunert** [comment]
> 1. I can't think of any issues enabling linear history for the master branch. What do you think?

We already have it enabled, right? :)

> 2. This is a `false positive`, as status checks are enabled for `master`. No action required here.

Agree :+1: 

> 3. The state dismissal can be a problem for us whilst we have some long running/flake tests. I think we could keep as is and review it after further improvements on test suite.

About which kind of dismissal are we speaking about here? Something like the integration of a stale bot?

> 4. / 5. / 6. This may be due to the fact that "Include Administrators" is disabled - probably the same is for number 2. Do you think doing the below may break our merge automation?
>    
>    * Enable `Include Administrators`
>    * Enable `Require a pull request before merging`
>    * Add `k8s-ci-robot` to `Restrict who can push to matching branches`

We could give it a try! :)

**Comment by saschagrunert** [comment]
@pjbgf changed the branch protection rule for `master`, let's see what it breaks.

**Comment by pjbgf** [comment]
@saschagrunert nice one, let's hope it all works out.

By the way, the linear history for master branch still shows as disabled for me:
![image](https://user-images.githubusercontent.com/5452977/141281694-e9d80783-d18d-45be-95e6-d5dbcfa03d82.png)

So we are probably not refering to the same thing. :)

**Comment by jhrozek** [comment]
On Thu, Nov 11, 2021 at 02:24:22AM -0800, Paulo Gomes wrote:
> @saschagrunert nice one, let's hope it all works out.
> 
> By the way, the linear history for master branch still shows as disabled for me:
> ![image](https://user-images.githubusercontent.com/5452977/141281694-e9d80783-d18d-45be-95e6-d5dbcfa03d82.png)
> 
> So we are probably not refering to the same thing. :)

But we don't have those horrible merge commits that GH uses by default
for whatever silly reason. Isn't that it?

**Comment by saschagrunert** [comment]
@pjbgf I changed it to require a linear history. 

It looks like that the other options from the branch protection were gone, so I hope that there is nothing like a nightly sync which enforces a certain branch protection ruleset within this org.

**Comment by pjbgf** [comment]
Will keep on until changes can be manually confirmed.

**Comment by pjbgf** [comment]
> But we don't have those horrible merge commits that GH uses by default for whatever silly reason. Isn't that it?

@jhrozek sorry missed your message here. But I also did not understand exactly what do you mean here, can you clarify please?

**Comment by pjbgf** [comment]
After a delay the changes were applied:

![image](https://user-images.githubusercontent.com/5452977/144297673-0a180bf4-92ac-495d-83ef-d4cca2b74e08.png)

![image](https://user-images.githubusercontent.com/5452977/144297703-5d73416f-0eeb-47fd-b4f7-e4d93814cbef.png)

Let's keep an eye in the comming days as to the impact this may have.
Closing it for the time being.

**Comment by jhrozek** [comment]
> > But we don't have those horrible merge commits that GH uses by default for whatever silly reason. Isn't that it?
> 
> @jhrozek sorry missed your message here. But I also did not understand exactly what do you mean here, can you clarify please?

No problem,  I probably meant something else than you, Sascha and the scorecard meant. I thought we already did have linear history because I don't see merge commits in SPO like I see e.g. in selinuxd (https://github.com/containers/selinuxd/commits/main)
