### ISSUE TITLE
Add validating and admission plug-ins as requirements in the documentation. They are enabled by default in OpenShift but not in RKE2.

### ISSUE THREAD

**Issue by marcredhat** [kubernetes-sigs/security-profiles-operator#667]
#### What happened:
Default validating and admission plug-ins are enabled in OpenShift Container Platform 4.7.
https://docs.openshift.com/container-platform/4.7/architecture/admission-plug-ins.html#validating-admission-plug-in_admission-plug-ins

For RKE2, --enable-admission-plugins= in kube_apiserver_extra_args  is needed as shown at https://gist.github.com/marcredhat/e0a18623c9bf465243eab1871bcd7237

Without --enable-admission-plugins as shown in the above gist, 
cert-manager and security-profiles-operator won't work on RKE2. 

Using https://gist.github.com/marcredhat/e0a18623c9bf465243eab1871bcd7237,
the Security Profiles Operator gets deployed without any issues as shown below.

#### Environment:

**k get pods -n security-profiles-operator**
NAME                                                  READY   STATUS    RESTARTS   AGE
security-profiles-operator-54d479469f-v56xj           1/1     Running   0          16m
security-profiles-operator-54d479469f-xrjx7           1/1     Running   0          16m
security-profiles-operator-54d479469f-ztsh9           1/1     Running   0          16m
security-profiles-operator-webhook-655bbb7998-f4fg8   1/1     Running   0          16m
security-profiles-operator-webhook-655bbb7998-f9js8   1/1     Running   0          16m
security-profiles-operator-webhook-655bbb7998-wfc7c   1/1     Running   0          16m
spod-2qls7                                            2/2     Running   0          16m
spod-mllnf                                            2/2     Running   0          16m
spod-pkqzj                                            2/2     Running   0          16m

**cat /etc/redhat-release**
CentOS Linux release 8.3.2011

**rke2 -version**
rke2 version v1.21.6+rke2r1 (b915fc986e84582458af7131fe7f4e686f2af493)
go version go1.16.6b7

**getenforce**
Enforcing

**cat /var/lib/rancher/rke2/agent/etc/containerd/config.toml |grep enable**
enable_selinux = true

**ps -eZ | grep -E 'containerd'**
system_u:system_r:container_runtime_t:s0 15360 ? 00:01:11 containerd
...

**seinfo -acontainer_domain -x**
Type Attributes: 1
   attribute container_domain;
	container_engine_t
	container_init_t
	container_kvm_t
	container_logreader_t
	container_t
	container_userns_t
	rke2_service_db_t
	rke2_service_t
	spc_t

**Comment by jhrozek** [comment]
Would you mind opening a PR against the installation and usage MD document?
