### ISSUE TITLE
recording of replicated pods should contain the union of the recorded policies

### ISSUE THREAD

**Issue by jhrozek** [kubernetes-sigs/security-profiles-operator#677]
#### What happened:
Recording of a replicated pod creates a policy per replica. Depending on what does each replica do during the recording, each policy might be a bit different with no easy way to merge the policies other than manually.

#### What you expected to happen:
Because the pods managed the replicating controller, be it a Deployment, a DeamonSet or a ReplicaSet should be interchangeable, I would expect the result to be an union of the recorded policies.

#### How to reproduce it (as minimally and precisely as possible):
Record a deployment, check out that the result present a policy per pod.

#### Anything else we need to know?:
N/A

#### Environment:

- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Comment by jhrozek** [comment]
I'm going to try tackling this
/assign

**Comment by jhrozek** [comment]
Sorry this is taking so long. I've been working on this on and off (mostly off as I've been pulled into other directions). So far my idea, after brainstorming with @JAORMX is:
 - add a new field 'ready' to all profile CRs. This would indicate if the profile should be taken into use right after recording.
 - profileRecording CRs would also have this field. Per-profile controllers would just not reconcile policies with ready=false
 - in addition, the profileRecording CR would also have a mergeStrategy, defaulting to 'none', as the current status. We could add 'mergeContainers` as the first addition
 - each new recorded policy would contain a link (details tbd, might be an ownership reference, a finalizer or something else)
 - a new controller would be added, reconciling profileRecordings. If the merge strategy is set to merge containers AND the profilerecording is being deleted, the controller would list all recorded policies generated using this recording which are ready=false and merge them into a resulting policy which would be created. Only at that point would the recording be really deleted.

Hope this makes sense design-wise.

**Comment by saschagrunert** [comment]
> * add a new field 'ready' to all profile CRs. This would indicate if the profile should be taken into use right after recording.

Reflecting that in a status field seems reasonable to me! :) 

> * a new controller would be added, reconciling profileRecordings. If the merge strategy is set to merge containers AND the profilerecording is being deleted, the controller would list all recorded policies generated using this recording which are ready=false and merge them into a resulting policy which would be created. Only at that point would the recording be really deleted.

Yep, this seems to be the way to approach this. :+1:

**Comment by jhrozek** [comment]
I'm 90% done (currently adding tests)
/remove-lifecycle rotten
