### ISSUE TITLE
AppArmor MVP

### ISSUE THREAD

**Issue by pjbgf** [kubernetes-sigs/security-profiles-operator#718]
#### What would you like to be added:

High-level issue to capture outstanding items for AppArmor's MVP. 
Targeting release https://github.com/kubernetes-sigs/security-profiles-operator/issues/613.

- [ ] https://github.com/kubernetes-sigs/security-profiles-operator/issues/1491
- [x] Documentation (Usage, Requirements, Examples)
- [x] https://github.com/kubernetes-sigs/security-profiles-operator/pull/1684
- [x] https://github.com/kubernetes-sigs/security-profiles-operator/pull/1298
- [x] Fail-safe mechanism - improve user visibility to end-user when AppArmor is not enforceable
- [x] Add liveness/startup probe
- [x] Allow daemon to be ready even if no Profile has been deployed

#### Why is this needed:

The current AppArmor support is not production ready. It lacks functionality, documentation and tests which are required to make it easier for the community to use and rely on it.

#### User story covered

As an application SRE, Rajesh would like to deploy a Seccomp profile and an SELinux or AppArmor profiles to secure their application.

**Comment by hacst** [comment]
@pjbgf Thanks a lot for working on this. I see the latest PR removes the "WIP" notes from the README. Does that mean it is ready to test? Should we wait for #1308 ? It is a bit hard to judge the state of this implementation from the outside so any insight you can give with regards to state (or even timeline) on this would be great. Thanks again.

**Comment by pjbgf** [comment]
@hacst feel free to test it, we have released a version Today with it.

There are plenty of improvements to come, but the basic functionality should already be in place.
