### ISSUE TITLE
Do memory and CPU benchmark

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/security-profiles-operator#736]
Benchmarking the SPOD containers with a manual test and adjust the resources accordingly before doing the release.

**Comment by saschagrunert** [comment]
I’ll do the BPF recorder first tomorrow.

**Comment by saschagrunert** [comment]
bpf recorder results while doing a test with 10 and later with 50 pod recordings in parallel on 3 worker nodes:
![screenshot](https://user-images.githubusercontent.com/695473/144398525-da5c73d7-957b-4d9e-9680-c05e11fee144.png)

Looks like our current memory restrictions are good enough:
https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/internal/pkg/manager/spod/bindata/spod.go#L501-L506

**Comment by saschagrunert** [comment]
Did a 10 minute test with 50 pods recordings via the log enricher, the new memory values seems to pay out:
![screenshot](https://user-images.githubusercontent.com/695473/145055181-bec0a1dc-63be-4018-a706-793e0dcd45fa.png)

**Comment by saschagrunert** [comment]
@jhrozek I'm done with testing, feel free to reopen if you see anything left open.

**Comment by jhrozek** [comment]
On Tue, Dec 07, 2021 at 07:13:54AM -0800, Sascha Grunert wrote:
> @jhrozek I'm done with testing, feel free to reopen if you see anything left open.

The only thing I found on my side is the webhook race which is already
filed an a selinuxd memory leak for which I still
don't have a patch. Looks like most of the issues were triggered by
seccomp due to the bigger size of the logs..
