### ISSUE TITLE
Cannot apply operator manifests in K3s 1.22.3+k3s1

### ISSUE THREAD

**Issue by timoschwarzer** [kubernetes-sigs/security-profiles-operator#760]
#### What happened:
Trying to apply the operator fails to create the SeccompProfile CRD with an error:

```
The CustomResourceDefinition "seccompprofiles.security-profiles-operator.x-k8s.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
```

#### How to reproduce it (as minimally and precisely as possible):
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/main/deploy/operator.yaml
```

#### Anything else we need to know?:
-/-

#### Environment:

- Cloud provider or hardware configuration: 3 bare metal worker nodes, 1 server node
- OS (e.g: `cat /etc/os-release`): Ubuntu Server 20.04.3 LTS
- Kernel (e.g. `uname -a`): 5.4.0-91-generic
- Others: K3s 1.22.4+k3s1

**Comment by saschagrunert** [comment]
@timoschwarzer is it correct that this is an upgrade scenario?

**Comment by timoschwarzer** [comment]
@saschagrunert I tried both upgrading and deleting the whole namespace before applying, neither of which worked.

**Comment by saschagrunert** [comment]
> @saschagrunert I tried both upgrading and deleting the whole namespace before applying, neither of which worked.

Can you please try to explicitly remove the CRD? This is not part of the namespace but available on a cluster level.

**Comment by timoschwarzer** [comment]
@saschagrunert Thank you for the suggestion! Removing the finalizer from the CRD and deleting it before applying the new manifest indeed fixed the problem.

**Comment by saschagrunert** [comment]
@timoschwarzer I think we still have an upgrade path problem here. 

@pjbgf @jhrozek @JAORMX do you think we have to address this before 0.4.0?

**Comment by jhrozek** [comment]
On Fri, Dec 10, 2021 at 05:40:19AM -0800, Sascha Grunert wrote:
> @timoschwarzer I think we still have an upgrade path problem here. 
> 
> @pjbgf @jhrozek @JAORMX do you think we have to address this before 0.4.0?

Do we know what the issue is? Would we need a conversion webhook?

**Comment by saschagrunert** [comment]
> Would we need a conversion webhook?

Yes I think so.

**Comment by pjbgf** [comment]
Probably a nice to have, so let's target it for v0.4.0 (https://github.com/kubernetes-sigs/security-profiles-operator/issues/613). In the meantime will keep this issue open.
