### ISSUE TITLE
Reduce code duplication in workloadannotator

### ISSUE THREAD

**Issue by Vincent056** [kubernetes-sigs/security-profiles-operator#887]
We added support for SELinux profile binding:https://github.com/kubernetes-sigs/security-profiles-operator/pull/854

However, there are some code duplications in
 https://github.com/kubernetes-sigs/security-profiles-operator/blob/de3017ad869867efb9743a1c387398e7741fd3cc/internal/pkg/manager/workloadannotator/workloadannotator.go#L200

Since we will also add profile binding in the future for AppArmor. Under the current method, we will have more duplication.
we should create an interface that all security profiles that support bindings would implement and then pass a variable implementing that interface to the update function.

**Comment by saschagrunert** [comment]
Awesome, thank you for considering to work on this @Vincent056! :pray:

**Comment by jhrozek** [comment]
/remove-lifecycle stale
@Vincent056 I propose we look at this after in ~3 weeks (after our upcoming sprint)
