### ISSUE TITLE
used ebpf to record container behavior, but found that I could not record syscall in the shell script running process in the container. 

### ISSUE THREAD

**Issue by longpi1** [kubernetes-sigs/security-profiles-operator#903]
#### What happened:
Hello, I recently used ebpf to record container behavior, but found that I could not record syscall in the shell script running process in the container. As a result, some functions of pod could not be used normally after I mounted JSON files.
#### What you expected to happen:
Syscall can also be recorded normally during script execution in the container。
#### How to reproduce it (as minimally and precisely as possible):
Execute shell script inside POD
#### Environment:
Linux k8s-master-node-1 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
Hey @longpi1, may I ask you to share the container image for the reproducer?
