### ISSUE TITLE
An alternative to nix-build in Dockerfile

### ISSUE THREAD

**Issue by longpi1** [kubernetes-sigs/security-profiles-operator#926]
#### What would you like to be added:
Hello, I want to build images in Dockerfile without passing Nix
#### Why is this needed:
In my own virtual environment, I do not have nix proxy source, so I cannot download the corresponding package. Is there any other way that I can key mirror without NIx?
#### User story covered
I want to modify part of the code and build the corresponding image for testing, but I cannot download the corresponding package through nix-build at present

**Comment by saschagrunert** [comment]
Which alternative would work for you? Can you build the UBI based Dockerfile: https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/Dockerfile.ubi ?

**Comment by longpi1** [comment]
> Which alternative would work for you? Can you build the UBI based Dockerfile: https://github.com/kubernetes-sigs/security-profiles-operator/blob/main/Dockerfile.ubi ?
An error occurs when I use Dockerfile.ubi compile, as follows:
Microdnf install error:
(microDNF :1): glib-error **: 01:38:56.910: file.. /glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
Can I compile directly from a makefile or other means? Thank you very much！

**Comment by saschagrunert** [comment]
@longpi1 yes, does a simple `make` work for you?
