### ISSUE TITLE
Provide Helm chart artifact for installation

### ISSUE THREAD

**Issue by JAORMX** [kubernetes-sigs/security-profiles-operator#985]
#### What would you like to be added:

As part of the releases of this operator, we should also release Helm charts.

#### Why is this needed:

The Security Profiles Operator currently provides two modes of installation:

* Kustomize-generated manifests
* Operator Lifecycle Manager bundle

There are a lot of organizations who depend on Helm to install Kubernetes packages, so it would be ideal to also provide a Helm Chart as means of installation

#### User story covered

All? This would enable more folks to install the Security Profiles Operator through their preferred means.

**Comment by stephen-fox** [comment]
Comment!
